# ethmin: a picorv32 SoC with a 1G Ethernet MAC and a LiteEth SGMII PCS,
# ported from vc707-openflow-demos.  See README.md for provenance.
#
# Order matters only in that yosys reads them all before elaborating; the
# top is vc707_ethmin.

# The SoC
rtl/picorv32.v
rtl/simpleuart.v
rtl/spimemio.v
rtl/picosoc_mem_dp.v
rtl/picosoc_ethmin.v
rtl/progmem_ethmin.v

# Ethernet: MAC, framing, buffering, DMA
rtl/eth_mac_1g.sv
rtl/axis_gmii_rx.sv
rtl/axis_gmii_tx.sv
rtl/rgmii_lfsr.sv
rtl/eth_lutram_fifo.sv
rtl/eth_stream_dma.sv
rtl/eth_gmii_retime256.sv
rtl/eth_pkt_buf256.sv

# The SGMII physical layer, generated by LiteEth, and its wrapper
rtl/liteeth_sgmii_phy.v
rtl/sgmii_soc_liteeth.sv

# Clocking and the top level
rtl/clkgen_vc707.sv
rtl/ethmin_core.v
rtl/vc707_ethmin.v
