// -----------------------------------------------------------------------------
// GENERATED FILE -- do not edit.  Produced by ethmin/liteeth_phy/gen_liteeth_phy.py
//
// A standalone SGMII/1000BASE-X PHY: LiteEth's PCS driving a GTXE2 transceiver,
// presented as an ordinary GMII interface.
//
// Derived from, and containing code generated by:
//   LiteEth      Copyright (c) 2012-2024 EnjoyDigital and contributors
//   LiteICLink   Copyright (c) 2017-2024 EnjoyDigital and contributors
//   migen        Copyright (c) 2011-2024 M-Labs Limited and contributors
//   LiteX        Copyright (c) 2012-2024 EnjoyDigital and contributors
// all under the BSD 2-Clause Licence, which permits redistribution in source
// and binary form provided the above notice and the disclaimer are retained.
// See https://github.com/enjoy-digital/liteeth for the full text.
//
// The generator script and the surrounding SoC are ISC-licensed; see LICENSE.
// -----------------------------------------------------------------------------

/* Machine-generated using Migen */
module liteeth_sgmii_phy(
	input clk_int,
	input rst_int,
	input sgmii_refclk_p,
	input sgmii_refclk_n,
	output sgmii_txp,
	output sgmii_txn,
	input sgmii_rxp,
	input sgmii_rxn,
	output gmii_tx_clk,
	input [7:0] gmii_txd,
	input gmii_tx_en,
	output gmii_rx_clk,
	output [7:0] gmii_rxd,
	output gmii_rx_dv,
	output gmii_rx_er,
	output link_up,
	output phy_ready
);

wire sys_clk;
wire sys_rst;
reg k7_1000basex_pcs_pcstx_config_valid;
reg [15:0] k7_1000basex_pcs_pcstx_config_reg;
reg [1:0] k7_1000basex_pcs_pcstx_sgmii_speed;
wire k7_1000basex_pcs_pcstx_sink_valid;
reg k7_1000basex_pcs_pcstx_sink_ready;
wire k7_1000basex_pcs_pcstx_sink_first;
wire k7_1000basex_pcs_pcstx_sink_last;
wire [7:0] k7_1000basex_pcs_pcstx_sink_payload_data;
reg k7_1000basex_pcs_pcstx_encoder_ce0 = 1'd1;
reg [7:0] k7_1000basex_pcs_pcstx_encoder0;
reg k7_1000basex_pcs_pcstx_encoder1;
reg [9:0] k7_1000basex_pcs_pcstx_encoder2 = 10'd0;
reg k7_1000basex_pcs_pcstx_encoder3 = 1'd0;
wire [7:0] k7_1000basex_pcs_pcstx_encoder_d;
wire k7_1000basex_pcs_pcstx_encoder_k;
reg k7_1000basex_pcs_pcstx_encoder_disp_in = 1'd0;
reg [9:0] k7_1000basex_pcs_pcstx_encoder_output;
reg k7_1000basex_pcs_pcstx_encoder_disp_out;
reg [5:0] k7_1000basex_pcs_pcstx_encoder_code6b = 6'd0;
reg k7_1000basex_pcs_pcstx_encoder_code6b_unbalanced = 1'd0;
reg k7_1000basex_pcs_pcstx_encoder_code6b_flip = 1'd0;
reg [3:0] k7_1000basex_pcs_pcstx_encoder_code4b = 4'd0;
reg k7_1000basex_pcs_pcstx_encoder_code4b_unbalanced = 1'd0;
reg k7_1000basex_pcs_pcstx_encoder_code4b_flip = 1'd0;
reg k7_1000basex_pcs_pcstx_encoder_alt7_rd0 = 1'd0;
reg k7_1000basex_pcs_pcstx_encoder_alt7_rd1 = 1'd0;
reg [5:0] k7_1000basex_pcs_pcstx_encoder_output_6b;
wire k7_1000basex_pcs_pcstx_encoder_disp_inter;
reg [3:0] k7_1000basex_pcs_pcstx_encoder_output_4b;
wire [9:0] k7_1000basex_pcs_pcstx_encoder_output_msb_first;
wire k7_1000basex_pcs_pcstx_encoder_ce1;
reg k7_1000basex_pcs_pcstx_count0 = 1'd0;
reg k7_1000basex_pcs_pcstx_parity = 1'd0;
reg k7_1000basex_pcs_pcstx_ctype = 1'd0;
reg k7_1000basex_pcs_pcstx_enable;
wire k7_1000basex_pcs_pcstx_done;
reg [6:0] k7_1000basex_pcs_pcstx_count1 = 7'd0;
reg k7_1000basex_pcs_pcsrx_seen_valid_ci;
reg k7_1000basex_pcs_pcsrx_seen_config_reg;
reg [15:0] k7_1000basex_pcs_pcsrx_config_reg = 16'd0;
reg [1:0] k7_1000basex_pcs_pcsrx_sgmii_speed;
reg k7_1000basex_pcs_pcsrx_source_valid;
wire k7_1000basex_pcs_pcsrx_source_ready;
reg k7_1000basex_pcs_pcsrx_source_first;
reg k7_1000basex_pcs_pcsrx_source_last;
reg [7:0] k7_1000basex_pcs_pcsrx_source_payload_data;
reg k7_1000basex_pcs_pcsrx_source_payload_error;
reg k7_1000basex_pcs_pcsrx_decoder_ce = 1'd1;
wire [9:0] k7_1000basex_pcs_pcsrx_decoder_input;
wire [7:0] k7_1000basex_pcs_pcsrx_decoder_d;
reg k7_1000basex_pcs_pcsrx_decoder_k = 1'd0;
wire k7_1000basex_pcs_pcsrx_decoder_invalid;
reg [9:0] k7_1000basex_pcs_pcsrx_decoder_input_msb_first;
wire [4:0] k7_1000basex_pcs_pcsrx_decoder_code5b;
reg [2:0] k7_1000basex_pcs_pcsrx_decoder_code3b = 3'd0;
wire [5:0] k7_1000basex_pcs_pcsrx_decoder_adr;
wire [4:0] k7_1000basex_pcs_pcsrx_decoder_dat_r;
wire k7_1000basex_pcs_pcsrx_decoder_re;
reg [3:0] k7_1000basex_pcs_pcsrx_decoder_ones = 4'd0;
reg k7_1000basex_pcs_pcsrx_count0 = 1'd0;
reg k7_1000basex_pcs_pcsrx_enable;
wire k7_1000basex_pcs_pcsrx_done;
reg [6:0] k7_1000basex_pcs_pcsrx_count1 = 7'd0;
wire k7_1000basex_pcs_pcsrx_timer_ce;
reg k7_1000basex_pcs_pcsrx_sink_sink_valid;
wire k7_1000basex_pcs_pcsrx_sink_sink_ready;
reg k7_1000basex_pcs_pcsrx_sink_sink_first = 1'd0;
reg k7_1000basex_pcs_pcsrx_sink_sink_last = 1'd0;
reg [7:0] k7_1000basex_pcs_pcsrx_sink_sink_payload_data;
wire k7_1000basex_pcs_pcsrx_source_source_valid;
reg k7_1000basex_pcs_pcsrx_source_source_ready;
wire k7_1000basex_pcs_pcsrx_source_source_first;
wire k7_1000basex_pcs_pcsrx_source_source_last;
wire [7:0] k7_1000basex_pcs_pcsrx_source_source_payload_data;
wire k7_1000basex_pcs_pcsrx_pipe_valid_sink_valid;
wire k7_1000basex_pcs_pcsrx_pipe_valid_sink_ready;
wire k7_1000basex_pcs_pcsrx_pipe_valid_sink_first;
wire k7_1000basex_pcs_pcsrx_pipe_valid_sink_last;
wire [7:0] k7_1000basex_pcs_pcsrx_pipe_valid_sink_payload_data;
reg k7_1000basex_pcs_pcsrx_pipe_valid_source_valid = 1'd0;
wire k7_1000basex_pcs_pcsrx_pipe_valid_source_ready;
reg k7_1000basex_pcs_pcsrx_pipe_valid_source_first = 1'd0;
reg k7_1000basex_pcs_pcsrx_pipe_valid_source_last = 1'd0;
reg [7:0] k7_1000basex_pcs_pcsrx_pipe_valid_source_payload_data = 8'd0;
wire k7_1000basex_pcs_sink_sink_valid;
wire k7_1000basex_pcs_sink_sink_ready;
reg k7_1000basex_pcs_sink_sink_first = 1'd0;
wire k7_1000basex_pcs_sink_sink_last;
wire [7:0] k7_1000basex_pcs_sink_sink_payload_data;
wire k7_1000basex_pcs_source_source_valid;
wire k7_1000basex_pcs_source_source_ready;
wire k7_1000basex_pcs_source_source_first;
wire k7_1000basex_pcs_source_source_last;
wire [7:0] k7_1000basex_pcs_source_source_payload_data;
wire k7_1000basex_pcs_source_source_payload_error;
reg k7_1000basex_pcs_link_up;
reg k7_1000basex_pcs_restart;
reg k7_1000basex_pcs_align;
reg [15:0] k7_1000basex_pcs_lp_abi_i = 16'd0;
reg [15:0] k7_1000basex_pcs_lp_abi_o = 16'd0;
reg k7_1000basex_pcs_lp_abi_starter = 1'd1;
wire k7_1000basex_pcs_lp_abi_ping_i;
wire k7_1000basex_pcs_lp_abi_ping_o0;
reg k7_1000basex_pcs_lp_abi_ping_toggle_i = 1'd0;
wire k7_1000basex_pcs_lp_abi_ping_toggle_o;
reg k7_1000basex_pcs_lp_abi_ping_toggle_o_r = 1'd0;
reg k7_1000basex_pcs_lp_abi_ping_o1 = 1'd0;
wire k7_1000basex_pcs_lp_abi_pong_i;
wire k7_1000basex_pcs_lp_abi_pong_o;
reg k7_1000basex_pcs_lp_abi_pong_toggle_i = 1'd0;
wire k7_1000basex_pcs_lp_abi_pong_toggle_o;
reg k7_1000basex_pcs_lp_abi_pong_toggle_o_r = 1'd0;
wire k7_1000basex_pcs_lp_abi_wait;
wire k7_1000basex_pcs_lp_abi_done;
reg [7:0] k7_1000basex_pcs_lp_abi_count = 8'd128;
(* no_retiming = "true" *) reg [15:0] k7_1000basex_pcs_lp_abi_ibuffer = 16'd0;
wire [15:0] k7_1000basex_pcs_lp_abi_obuffer;
reg k7_1000basex_pcs_config_empty;
wire k7_1000basex_pcs_is_sgmii;
reg k7_1000basex_pcs_linkdown;
reg k7_1000basex_pcs_autoneg_ack;
wire k7_1000basex_pcs_seen_valid_ci_i;
wire k7_1000basex_pcs_seen_valid_ci_o;
reg k7_1000basex_pcs_seen_valid_ci_toggle_i = 1'd0;
wire k7_1000basex_pcs_seen_valid_ci_toggle_o;
reg k7_1000basex_pcs_seen_valid_ci_toggle_o_r = 1'd0;
reg k7_1000basex_pcs_rx_config_reg_abi_i = 1'd0;
wire k7_1000basex_pcs_rx_config_reg_abi_o;
reg k7_1000basex_pcs_rx_config_reg_abi_toggle_i = 1'd0;
wire k7_1000basex_pcs_rx_config_reg_abi_toggle_o;
reg k7_1000basex_pcs_rx_config_reg_abi_toggle_o_r = 1'd0;
reg k7_1000basex_pcs_rx_config_reg_ack_i = 1'd0;
wire k7_1000basex_pcs_rx_config_reg_ack_o;
reg k7_1000basex_pcs_rx_config_reg_ack_toggle_i = 1'd0;
wire k7_1000basex_pcs_rx_config_reg_ack_toggle_o;
reg k7_1000basex_pcs_rx_config_reg_ack_toggle_o_r = 1'd0;
reg k7_1000basex_pcs_waittimer0_wait;
wire k7_1000basex_pcs_waittimer0_done;
reg [20:0] k7_1000basex_pcs_waittimer0_count = 21'd1250000;
reg k7_1000basex_pcs_waittimer1_wait;
wire k7_1000basex_pcs_waittimer1_done;
reg [20:0] k7_1000basex_pcs_waittimer1_count = 21'd1250000;
reg k7_1000basex_pcs_waittimer2_wait;
wire k7_1000basex_pcs_waittimer2_done;
reg [17:0] k7_1000basex_pcs_waittimer2_count = 18'd200000;
reg [19:0] k7_1000basex_pcs_checker_count = 20'd0;
reg k7_1000basex_pcs_checker_tick = 1'd0;
reg k7_1000basex_pcs_checker_error = 1'd0;
wire k7_1000basex_pcs_sgmii_speed_valid;
wire [1:0] k7_1000basex_pcs_sgmii_tx_speed;
wire [1:0] k7_1000basex_pcs_sgmii_rx_speed;
reg [3:0] k7_1000basex_pcs_rx_config_reg_count = 4'd0;
reg [15:0] k7_1000basex_pcs_rx_config_reg_last = 16'd0;
wire eth_tx_clk;
wire eth_tx_rst;
wire eth_rx_clk;
wire eth_rx_rst;
wire eth_tx_half_clk;
wire eth_rx_half_clk;
wire k7_1000basex_txoutclk;
wire k7_1000basex_rxoutclk;
reg k7_1000basex_reset = 1'd0;
wire k7_1000basex_refclk;
wire k7_1000basex_tx_reset;
wire k7_1000basex_tx_mmcm_locked0;
(* no_retiming = "true" *) reg k7_1000basex_tx_mmcm_reset0 = 1'd1;
wire [19:0] k7_1000basex_tx_data0;
wire k7_1000basex_tx_reset_done;
wire k7_1000basex_rx_reset;
wire k7_1000basex_rx_mmcm_locked0;
(* no_retiming = "true" *) reg k7_1000basex_rx_mmcm_reset0 = 1'd1;
wire [19:0] k7_1000basex_rx_data0;
wire k7_1000basex_rx_reset_done;
wire k7_1000basex_pll_reset;
wire k7_1000basex_pll_lock;
wire k7_1000basex0;
wire k7_1000basex1;
wire k7_1000basex2;
wire k7_1000basex3;
wire k7_1000basex4;
wire k7_1000basex5;
wire k7_1000basex6;
wire k7_1000basex7;
wire k7_1000basex8;
wire k7_1000basex9;
wire k7_1000basex10;
wire k7_1000basex11;
wire k7_1000basex12;
wire k7_1000basex13;
wire k7_1000basex14;
wire k7_1000basex15;
wire k7_1000basex16;
wire k7_1000basex17;
wire k7_1000basex18;
wire k7_1000basex19;
wire k7_1000basex20;
wire k7_1000basex21;
wire k7_1000basex22;
wire k7_1000basex23;
wire k7_1000basex24;
wire k7_1000basex25;
wire k7_1000basex26;
wire k7_1000basex27;
wire k7_1000basex28;
wire k7_1000basex29;
wire k7_1000basex30;
wire k7_1000basex31;
wire k7_1000basex32;
wire k7_1000basex33;
wire k7_1000basex34;
wire k7_1000basex35;
wire k7_1000basex36;
wire k7_1000basex37;
wire k7_1000basex38;
wire k7_1000basex39;
wire k7_1000basex40;
wire k7_1000basex41;
wire k7_1000basex42;
wire k7_1000basex43;
wire k7_1000basex44;
wire k7_1000basex45;
wire k7_1000basex46;
wire k7_1000basex47;
wire k7_1000basex48;
wire k7_1000basex49;
wire k7_1000basex50;
wire k7_1000basex51;
wire k7_1000basex52;
wire k7_1000basex53;
wire k7_1000basex_txoutclk_rebuffer;
wire k7_1000basex_rxoutclk_rebuffer;
wire k7_1000basex_tx_mmcm_reset1;
reg k7_1000basex_tx_mmcm_power_down = 1'd0;
wire k7_1000basex_tx_mmcm_locked1;
wire k7_1000basex_s7mmcm0_clkin_signal;
wire k7_1000basex_s7mmcm0_clkout0;
wire k7_1000basex_s7mmcm0_clkout_buf0;
wire k7_1000basex_s7mmcm0_clkout1;
wire k7_1000basex_s7mmcm0_clkout_buf1;
wire k7_1000basex_rx_mmcm_reset1;
reg k7_1000basex_rx_mmcm_power_down = 1'd0;
wire k7_1000basex_rx_mmcm_locked1;
wire k7_1000basex_s7mmcm1_clkin_signal;
wire k7_1000basex_s7mmcm1_clkout0;
wire k7_1000basex_s7mmcm1_clkout_buf0;
wire k7_1000basex_s7mmcm1_clkout1;
wire k7_1000basex_s7mmcm1_clkout_buf1;
reg k7_1000basex_gtxtxinit_done;
reg k7_1000basex_gtxtxinit_restart = 1'd0;
wire k7_1000basex_gtxtxinit_plllock0;
reg k7_1000basex_gtxtxinit_pllreset0 = 1'd0;
reg k7_1000basex_gtxtxinit_gtXxreset0 = 1'd0;
reg k7_1000basex_gtxtxinit_gtXxpd0 = 1'd0;
wire k7_1000basex_gtxtxinit_Xxresetdone0;
reg k7_1000basex_gtxtxinit_Xxdlysreset0 = 1'd0;
reg k7_1000basex_gtxtxinit_Xxdlysresetdone0 = 1'd0;
reg k7_1000basex_gtxtxinit_Xxphaligndone0 = 1'd0;
reg k7_1000basex_gtxtxinit_Xxuserrdy0 = 1'd0;
reg k7_1000basex_gtxtxinit_drp_start;
reg k7_1000basex_gtxtxinit_drp_done = 1'd1;
wire k7_1000basex_gtxtxinit_plllock1;
wire k7_1000basex_gtxtxinit_Xxresetdone1;
wire k7_1000basex_gtxtxinit_Xxdlysresetdone1;
wire k7_1000basex_gtxtxinit_Xxphaligndone1;
reg k7_1000basex_gtxtxinit_Xxphaligndone_r = 1'd1;
wire k7_1000basex_gtxtxinit_Xxphaligndone_rising;
reg k7_1000basex_gtxtxinit_pllreset1;
reg k7_1000basex_gtxtxinit_gtXxreset1;
reg k7_1000basex_gtxtxinit_gtXxpd1;
reg k7_1000basex_gtxtxinit_Xxdlysreset1;
reg k7_1000basex_gtxtxinit_Xxuserrdy1;
wire k7_1000basex_gtxtxinit_reset;
wire k7_1000basex_gtxtxinit_init_delay_wait;
wire k7_1000basex_gtxtxinit_init_delay_done;
reg [3:0] k7_1000basex_gtxtxinit_init_delay_count = 4'd12;
reg k7_1000basex_gtxtxinit_cdr_lock_timer_wait;
wire k7_1000basex_gtxtxinit_cdr_lock_timer_done;
reg [10:0] k7_1000basex_gtxtxinit_cdr_lock_timer_count = 11'd1024;
wire k7_1000basex_gtxtxinit_watchdog_wait;
wire k7_1000basex_gtxtxinit_watchdog_done;
reg [14:0] k7_1000basex_gtxtxinit_watchdog_count = 15'd25000;
wire k7_1000basex_tx_init_reset;
reg k7_1000basex_gtxrxinit_done;
wire k7_1000basex_gtxrxinit_restart;
wire k7_1000basex_gtxrxinit_plllock0;
reg k7_1000basex_gtxrxinit_pllreset0 = 1'd0;
reg k7_1000basex_gtxrxinit_gtXxreset0 = 1'd0;
reg k7_1000basex_gtxrxinit_gtXxpd0 = 1'd0;
wire k7_1000basex_gtxrxinit_Xxresetdone0;
reg k7_1000basex_gtxrxinit_Xxdlysreset0 = 1'd0;
reg k7_1000basex_gtxrxinit_Xxdlysresetdone0 = 1'd0;
reg k7_1000basex_gtxrxinit_Xxphaligndone0 = 1'd0;
reg k7_1000basex_gtxrxinit_Xxuserrdy0 = 1'd0;
reg k7_1000basex_gtxrxinit_drp_start;
reg k7_1000basex_gtxrxinit_drp_done = 1'd1;
wire k7_1000basex_gtxrxinit_plllock1;
wire k7_1000basex_gtxrxinit_Xxresetdone1;
wire k7_1000basex_gtxrxinit_Xxdlysresetdone1;
wire k7_1000basex_gtxrxinit_Xxphaligndone1;
reg k7_1000basex_gtxrxinit_Xxphaligndone_r = 1'd1;
wire k7_1000basex_gtxrxinit_Xxphaligndone_rising;
reg k7_1000basex_gtxrxinit_pllreset1;
reg k7_1000basex_gtxrxinit_gtXxreset1;
reg k7_1000basex_gtxrxinit_gtXxpd1;
reg k7_1000basex_gtxrxinit_Xxdlysreset1;
reg k7_1000basex_gtxrxinit_Xxuserrdy1;
wire k7_1000basex_gtxrxinit_reset;
wire k7_1000basex_gtxrxinit_init_delay_wait;
wire k7_1000basex_gtxrxinit_init_delay_done;
reg [3:0] k7_1000basex_gtxrxinit_init_delay_count = 4'd12;
reg k7_1000basex_gtxrxinit_cdr_lock_timer_wait;
wire k7_1000basex_gtxrxinit_cdr_lock_timer_done;
reg [10:0] k7_1000basex_gtxrxinit_cdr_lock_timer_count = 11'd1024;
wire k7_1000basex_gtxrxinit_watchdog_wait;
wire k7_1000basex_gtxrxinit_watchdog_done;
reg [14:0] k7_1000basex_gtxrxinit_watchdog_count = 15'd25000;
wire k7_1000basex_rx_init_reset;
wire k7_1000basex_i;
wire k7_1000basex_o;
reg k7_1000basex_toggle_i = 1'd0;
wire k7_1000basex_toggle_o;
reg k7_1000basex_toggle_o_r = 1'd0;
reg [9:0] k7_1000basex_cdr_lock_counter = 10'd0;
reg k7_1000basex_cdr_locked = 1'd0;
wire [9:0] k7_1000basex_tx_data1;
reg [19:0] k7_1000basex_tx_data_half = 20'd0;
wire [19:0] k7_1000basex_rx_data_half;
reg [9:0] k7_1000basex_rx_data1 = 10'd0;
reg [19:0] k7_1000basex_buf = 20'd0;
reg k7_1000basex_phase_half = 1'd0;
reg k7_1000basex_phase_half_rereg = 1'd0;
reg [2:0] clockdomainsrenamer0_state = 3'd0;
reg [2:0] clockdomainsrenamer0_next_state;
reg k7_1000basex_pcs_pcstx_count0_clockdomainsrenamer0_next_value0;
reg k7_1000basex_pcs_pcstx_count0_clockdomainsrenamer0_next_value_ce0;
reg k7_1000basex_pcs_pcstx_ctype_clockdomainsrenamer0_next_value1;
reg k7_1000basex_pcs_pcstx_ctype_clockdomainsrenamer0_next_value_ce1;
reg [2:0] clockdomainsrenamer1_state = 3'd0;
reg [2:0] clockdomainsrenamer1_next_state;
reg k7_1000basex_pcs_pcsrx_count0_clockdomainsrenamer1_next_value;
reg k7_1000basex_pcs_pcsrx_count0_clockdomainsrenamer1_next_value_ce;
reg [7:0] clockdomainsrenamer1_next_value0;
reg clockdomainsrenamer1_next_value_ce0;
reg [7:0] clockdomainsrenamer1_next_value1;
reg clockdomainsrenamer1_next_value_ce1;
reg [2:0] clockdomainsrenamer2_state = 3'd0;
reg [2:0] clockdomainsrenamer2_next_state;
wire s7mmcm0_reset0;
wire s7mmcm0_reset1;
wire s7mmcm0_reset2;
wire s7mmcm0_reset3;
wire s7mmcm0_reset4;
wire s7mmcm0_reset5;
wire s7mmcm0_reset6;
wire s7mmcm0_reset7;
wire s7mmcm0_mmcm_fb;
wire s7mmcm1_reset0;
wire s7mmcm1_reset1;
wire s7mmcm1_reset2;
wire s7mmcm1_reset3;
wire s7mmcm1_reset4;
wire s7mmcm1_reset5;
wire s7mmcm1_reset6;
wire s7mmcm1_reset7;
wire s7mmcm1_mmcm_fb;
reg [3:0] gtxtxinit_state = 4'd0;
reg [3:0] gtxtxinit_next_state;
reg [3:0] gtxrxinit_state = 4'd0;
reg [3:0] gtxrxinit_next_state;
reg [2:0] t_self0;
reg [2:0] t_self1;
reg [2:0] f_self;
reg [5:0] rhs_self0;
reg rhs_self1;
reg rhs_self2;
reg [3:0] rhs_self3;
reg rhs_self4;
reg rhs_self5;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl00 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl01 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl10 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl11 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg [15:0] xilinxmultiregimpl20 = 16'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg [15:0] xilinxmultiregimpl21 = 16'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl30 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl31 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl40 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl41 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl50 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl51 = 1'd0;
wire xilinxasyncresetsynchronizerimpl0;
wire xilinxasyncresetsynchronizerimpl0_rst_meta;
wire xilinxasyncresetsynchronizerimpl1;
wire xilinxasyncresetsynchronizerimpl1_rst_meta;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl60 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl61 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl70 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl71 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl80 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl81 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl90 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl91 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl100 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl101 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl110 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl111 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl120 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl121 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl130 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl131 = 1'd0;
(* async_reg = "true", mr_ff = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl140 = 1'd0;
(* async_reg = "true", no_retiming = "true", no_shreg_extract = "true" *) reg xilinxmultiregimpl141 = 1'd0;

// synthesis translate_off
reg dummy_s;
initial dummy_s <= 1'd0;
// synthesis translate_on

assign sys_clk = clk_int;
assign sys_rst = rst_int;
assign k7_1000basex_pcs_sink_sink_valid = gmii_tx_en;
assign k7_1000basex_pcs_sink_sink_payload_data = gmii_txd;
assign k7_1000basex_pcs_sink_sink_last = 1'd0;
assign k7_1000basex_pcs_source_source_ready = 1'd1;
assign gmii_rx_dv = k7_1000basex_pcs_source_source_valid;
assign gmii_rxd = k7_1000basex_pcs_source_source_payload_data;
assign gmii_rx_er = k7_1000basex_pcs_source_source_payload_error;
assign gmii_tx_clk = eth_tx_clk;
assign gmii_rx_clk = eth_rx_clk;
assign link_up = k7_1000basex_pcs_link_up;
assign phy_ready = (k7_1000basex_tx_mmcm_locked1 & k7_1000basex_rx_mmcm_locked1);
assign k7_1000basex_tx_mmcm_reset1 = k7_1000basex_tx_mmcm_reset0;
assign k7_1000basex_tx_mmcm_locked0 = k7_1000basex_tx_mmcm_locked1;
assign k7_1000basex_rx_mmcm_reset1 = k7_1000basex_rx_mmcm_reset0;
assign k7_1000basex_rx_mmcm_locked0 = k7_1000basex_rx_mmcm_locked1;
assign k7_1000basex_tx_init_reset = k7_1000basex_reset;
assign k7_1000basex_pll_reset = k7_1000basex_gtxtxinit_pllreset0;
assign k7_1000basex_gtxtxinit_plllock0 = k7_1000basex_pll_lock;
assign k7_1000basex_tx_reset = k7_1000basex_gtxtxinit_gtXxreset0;
assign k7_1000basex_gtxtxinit_Xxresetdone0 = k7_1000basex_tx_reset_done;
assign k7_1000basex_rx_init_reset = ((~k7_1000basex_gtxtxinit_done) | k7_1000basex_reset);
assign k7_1000basex_gtxrxinit_plllock0 = k7_1000basex_pll_lock;
assign k7_1000basex_rx_reset = k7_1000basex_gtxrxinit_gtXxreset0;
assign k7_1000basex_gtxrxinit_Xxresetdone0 = k7_1000basex_rx_reset_done;
assign k7_1000basex_i = k7_1000basex_pcs_restart;
assign k7_1000basex_gtxrxinit_restart = k7_1000basex_o;
assign k7_1000basex_tx_data0 = k7_1000basex_tx_data_half;
assign k7_1000basex_rx_data_half = k7_1000basex_rx_data0;
assign k7_1000basex_tx_data1 = k7_1000basex_pcs_pcstx_encoder2;
assign k7_1000basex_pcs_pcsrx_decoder_input = k7_1000basex_rx_data1;
assign k7_1000basex_pcs_pcstx_sink_valid = k7_1000basex_pcs_sink_sink_valid;
assign k7_1000basex_pcs_sink_sink_ready = k7_1000basex_pcs_pcstx_sink_ready;
assign k7_1000basex_pcs_pcstx_sink_first = k7_1000basex_pcs_sink_sink_first;
assign k7_1000basex_pcs_pcstx_sink_last = k7_1000basex_pcs_sink_sink_last;
assign k7_1000basex_pcs_pcstx_sink_payload_data = k7_1000basex_pcs_sink_sink_payload_data;
assign k7_1000basex_pcs_source_source_valid = k7_1000basex_pcs_pcsrx_source_valid;
assign k7_1000basex_pcs_pcsrx_source_ready = k7_1000basex_pcs_source_source_ready;
assign k7_1000basex_pcs_source_source_first = k7_1000basex_pcs_pcsrx_source_first;
assign k7_1000basex_pcs_source_source_last = k7_1000basex_pcs_pcsrx_source_last;
assign k7_1000basex_pcs_source_source_payload_data = k7_1000basex_pcs_pcsrx_source_payload_data;
assign k7_1000basex_pcs_source_source_payload_error = k7_1000basex_pcs_pcsrx_source_payload_error;
assign k7_1000basex_pcs_seen_valid_ci_i = k7_1000basex_pcs_pcsrx_seen_valid_ci;
assign k7_1000basex_pcs_is_sgmii = k7_1000basex_pcs_lp_abi_o[0];
assign k7_1000basex_pcs_sgmii_speed_valid = (k7_1000basex_pcs_lp_abi_o[11:10] != 2'd3);
assign k7_1000basex_pcs_sgmii_tx_speed = (k7_1000basex_pcs_sgmii_speed_valid ? k7_1000basex_pcs_lp_abi_o[11:10] : 2'd2);
assign k7_1000basex_pcs_sgmii_rx_speed = ((k7_1000basex_pcs_lp_abi_i[11:10] != 2'd3) ? k7_1000basex_pcs_lp_abi_i[11:10] : 2'd2);

// synthesis translate_off
reg dummy_d;
// synthesis translate_on
always @(*) begin
	k7_1000basex_pcs_pcstx_sgmii_speed <= 2'd0;
	k7_1000basex_pcs_pcsrx_sgmii_speed <= 2'd0;
	k7_1000basex_pcs_linkdown <= 1'd0;
	if ((~k7_1000basex_pcs_is_sgmii)) begin
		k7_1000basex_pcs_linkdown <= (k7_1000basex_pcs_lp_abi_o == 1'd0);
		k7_1000basex_pcs_pcstx_sgmii_speed <= 2'd2;
		k7_1000basex_pcs_pcsrx_sgmii_speed <= 2'd2;
	end else begin
		k7_1000basex_pcs_linkdown <= ((~k7_1000basex_pcs_lp_abi_o[15]) | (~k7_1000basex_pcs_sgmii_speed_valid));
		k7_1000basex_pcs_pcstx_sgmii_speed <= k7_1000basex_pcs_sgmii_tx_speed;
		k7_1000basex_pcs_pcsrx_sgmii_speed <= k7_1000basex_pcs_sgmii_rx_speed;
	end
// synthesis translate_off
	dummy_d <= dummy_s;
// synthesis translate_on
end

// synthesis translate_off
reg dummy_d_1;
// synthesis translate_on
always @(*) begin
	k7_1000basex_pcs_pcstx_config_reg <= 16'd0;
	if ((~k7_1000basex_pcs_config_empty)) begin
		k7_1000basex_pcs_pcstx_config_reg[0] <= k7_1000basex_pcs_is_sgmii;
		k7_1000basex_pcs_pcstx_config_reg[5] <= (~k7_1000basex_pcs_is_sgmii);
		if (k7_1000basex_pcs_is_sgmii) begin
			k7_1000basex_pcs_pcstx_config_reg[11:10] <= k7_1000basex_pcs_sgmii_tx_speed;
			k7_1000basex_pcs_pcstx_config_reg[12] <= 1'd1;
			k7_1000basex_pcs_pcstx_config_reg[15] <= k7_1000basex_pcs_link_up;
		end
		k7_1000basex_pcs_pcstx_config_reg[14] <= k7_1000basex_pcs_autoneg_ack;
	end
// synthesis translate_off
	dummy_d_1 <= dummy_s;
// synthesis translate_on
end
assign k7_1000basex_pcs_pcstx_encoder_ce1 = k7_1000basex_pcs_pcstx_encoder_ce0;
assign k7_1000basex_pcs_pcstx_encoder_d = k7_1000basex_pcs_pcstx_encoder0;
assign k7_1000basex_pcs_pcstx_encoder_k = k7_1000basex_pcs_pcstx_encoder1;
assign k7_1000basex_pcs_pcstx_encoder_disp_inter = (k7_1000basex_pcs_pcstx_encoder_disp_in ^ k7_1000basex_pcs_pcstx_encoder_code6b_unbalanced);

// synthesis translate_off
reg dummy_d_2;
// synthesis translate_on
always @(*) begin
	k7_1000basex_pcs_pcstx_encoder_output_6b <= 6'd0;
	if (((~k7_1000basex_pcs_pcstx_encoder_disp_in) & k7_1000basex_pcs_pcstx_encoder_code6b_flip)) begin
		k7_1000basex_pcs_pcstx_encoder_output_6b <= (~k7_1000basex_pcs_pcstx_encoder_code6b);
	end else begin
		k7_1000basex_pcs_pcstx_encoder_output_6b <= k7_1000basex_pcs_pcstx_encoder_code6b;
	end
// synthesis translate_off
	dummy_d_2 <= dummy_s;
// synthesis translate_on
end

// synthesis translate_off
reg dummy_d_3;
// synthesis translate_on
always @(*) begin
	k7_1000basex_pcs_pcstx_encoder_disp_out <= 1'd0;
	k7_1000basex_pcs_pcstx_encoder_output_4b <= 4'd0;
	if (((~k7_1000basex_pcs_pcstx_encoder_disp_inter) & k7_1000basex_pcs_pcstx_encoder_alt7_rd0)) begin
		k7_1000basex_pcs_pcstx_encoder_disp_out <= (~k7_1000basex_pcs_pcstx_encoder_disp_inter);
		k7_1000basex_pcs_pcstx_encoder_output_4b <= 3'd7;
	end else begin
		if ((k7_1000basex_pcs_pcstx_encoder_disp_inter & k7_1000basex_pcs_pcstx_encoder_alt7_rd1)) begin
			k7_1000basex_pcs_pcstx_encoder_disp_out <= (~k7_1000basex_pcs_pcstx_encoder_disp_inter);
			k7_1000basex_pcs_pcstx_encoder_output_4b <= 4'd8;
		end else begin
			k7_1000basex_pcs_pcstx_encoder_disp_out <= (k7_1000basex_pcs_pcstx_encoder_disp_inter ^ k7_1000basex_pcs_pcstx_encoder_code4b_unbalanced);
			if (((~k7_1000basex_pcs_pcstx_encoder_disp_inter) & k7_1000basex_pcs_pcstx_encoder_code4b_flip)) begin
				k7_1000basex_pcs_pcstx_encoder_output_4b <= (~k7_1000basex_pcs_pcstx_encoder_code4b);
			end else begin
				k7_1000basex_pcs_pcstx_encoder_output_4b <= k7_1000basex_pcs_pcstx_encoder_code4b;
			end
		end
	end
// synthesis translate_off
	dummy_d_3 <= dummy_s;
// synthesis translate_on
end
assign k7_1000basex_pcs_pcstx_encoder_output_msb_first = {k7_1000basex_pcs_pcstx_encoder_output_6b, k7_1000basex_pcs_pcstx_encoder_output_4b};

// synthesis translate_off
reg dummy_d_4;
// synthesis translate_on
always @(*) begin
	k7_1000basex_pcs_pcstx_encoder_output <= 10'd0;
	k7_1000basex_pcs_pcstx_encoder_output[0] <= k7_1000basex_pcs_pcstx_encoder_output_msb_first[9];
	k7_1000basex_pcs_pcstx_encoder_output[1] <= k7_1000basex_pcs_pcstx_encoder_output_msb_first[8];
	k7_1000basex_pcs_pcstx_encoder_output[2] <= k7_1000basex_pcs_pcstx_encoder_output_msb_first[7];
	k7_1000basex_pcs_pcstx_encoder_output[3] <= k7_1000basex_pcs_pcstx_encoder_output_msb_first[6];
	k7_1000basex_pcs_pcstx_encoder_output[4] <= k7_1000basex_pcs_pcstx_encoder_output_msb_first[5];
	k7_1000basex_pcs_pcstx_encoder_output[5] <= k7_1000basex_pcs_pcstx_encoder_output_msb_first[4];
	k7_1000basex_pcs_pcstx_encoder_output[6] <= k7_1000basex_pcs_pcstx_encoder_output_msb_first[3];
	k7_1000basex_pcs_pcstx_encoder_output[7] <= k7_1000basex_pcs_pcstx_encoder_output_msb_first[2];
	k7_1000basex_pcs_pcstx_encoder_output[8] <= k7_1000basex_pcs_pcstx_encoder_output_msb_first[1];
	k7_1000basex_pcs_pcstx_encoder_output[9] <= k7_1000basex_pcs_pcstx_encoder_output_msb_first[0];
// synthesis translate_off
	dummy_d_4 <= dummy_s;
// synthesis translate_on
end
assign k7_1000basex_pcs_pcstx_done = (k7_1000basex_pcs_pcstx_count1 == 1'd0);

// synthesis translate_off
reg dummy_d_5;
// synthesis translate_on
always @(*) begin
	k7_1000basex_pcs_pcstx_sink_ready <= 1'd0;
	k7_1000basex_pcs_pcstx_encoder0 <= 8'd0;
	k7_1000basex_pcs_pcstx_encoder1 <= 1'd0;
	k7_1000basex_pcs_pcstx_enable <= 1'd0;
	clockdomainsrenamer0_next_state <= 3'd0;
	k7_1000basex_pcs_pcstx_count0_clockdomainsrenamer0_next_value0 <= 1'd0;
	k7_1000basex_pcs_pcstx_count0_clockdomainsrenamer0_next_value_ce0 <= 1'd0;
	k7_1000basex_pcs_pcstx_ctype_clockdomainsrenamer0_next_value1 <= 1'd0;
	k7_1000basex_pcs_pcstx_ctype_clockdomainsrenamer0_next_value_ce1 <= 1'd0;
	clockdomainsrenamer0_next_state <= clockdomainsrenamer0_state;
	case (clockdomainsrenamer0_state)
		1'd1: begin
			case (k7_1000basex_pcs_pcstx_ctype)
				1'd0: begin
					k7_1000basex_pcs_pcstx_encoder0 <= 8'd181;
				end
				1'd1: begin
					k7_1000basex_pcs_pcstx_encoder0 <= 7'd66;
				end
			endcase
			k7_1000basex_pcs_pcstx_ctype_clockdomainsrenamer0_next_value1 <= (~k7_1000basex_pcs_pcstx_ctype);
			k7_1000basex_pcs_pcstx_ctype_clockdomainsrenamer0_next_value_ce1 <= 1'd1;
			clockdomainsrenamer0_next_state <= 2'd2;
		end
		2'd2: begin
			k7_1000basex_pcs_pcstx_count0_clockdomainsrenamer0_next_value0 <= (k7_1000basex_pcs_pcstx_count0 + 1'd1);
			k7_1000basex_pcs_pcstx_count0_clockdomainsrenamer0_next_value_ce0 <= 1'd1;
			case (k7_1000basex_pcs_pcstx_count0)
				1'd0: begin
					k7_1000basex_pcs_pcstx_encoder0 <= k7_1000basex_pcs_pcstx_config_reg[7:0];
				end
				1'd1: begin
					k7_1000basex_pcs_pcstx_encoder0 <= k7_1000basex_pcs_pcstx_config_reg[15:8];
				end
			endcase
			if ((k7_1000basex_pcs_pcstx_count0 == 1'd1)) begin
				clockdomainsrenamer0_next_state <= 1'd0;
			end
		end
		2'd3: begin
			case (k7_1000basex_pcs_pcstx_encoder3)
				1'd0: begin
					k7_1000basex_pcs_pcstx_encoder0 <= 8'd197;
				end
				1'd1: begin
					k7_1000basex_pcs_pcstx_encoder0 <= 7'd80;
				end
			endcase
			clockdomainsrenamer0_next_state <= 1'd0;
		end
		3'd4: begin
			k7_1000basex_pcs_pcstx_enable <= 1'd1;
			k7_1000basex_pcs_pcstx_sink_ready <= k7_1000basex_pcs_pcstx_done;
			if (k7_1000basex_pcs_pcstx_sink_valid) begin
				k7_1000basex_pcs_pcstx_encoder0 <= k7_1000basex_pcs_pcstx_sink_payload_data;
			end else begin
				k7_1000basex_pcs_pcstx_encoder1 <= 1'd1;
				k7_1000basex_pcs_pcstx_encoder0 <= 8'd253;
				clockdomainsrenamer0_next_state <= 3'd5;
			end
		end
		3'd5: begin
			k7_1000basex_pcs_pcstx_encoder1 <= 1'd1;
			k7_1000basex_pcs_pcstx_encoder0 <= 8'd247;
			if (k7_1000basex_pcs_pcstx_parity) begin
				clockdomainsrenamer0_next_state <= 1'd0;
			end
		end
		default: begin
			k7_1000basex_pcs_pcstx_encoder1 <= 1'd1;
			k7_1000basex_pcs_pcstx_encoder0 <= 8'd188;
			if (k7_1000basex_pcs_pcstx_config_valid) begin
				k7_1000basex_pcs_pcstx_count0_clockdomainsrenamer0_next_value0 <= 1'd0;
				k7_1000basex_pcs_pcstx_count0_clockdomainsrenamer0_next_value_ce0 <= 1'd1;
				clockdomainsrenamer0_next_state <= 1'd1;
			end else begin
				if (k7_1000basex_pcs_pcstx_sink_valid) begin
					k7_1000basex_pcs_pcstx_sink_ready <= k7_1000basex_pcs_pcstx_done;
					k7_1000basex_pcs_pcstx_encoder0 <= 8'd251;
					clockdomainsrenamer0_next_state <= 3'd4;
				end else begin
					clockdomainsrenamer0_next_state <= 2'd3;
				end
			end
		end
	endcase
// synthesis translate_off
	dummy_d_5 <= dummy_s;
// synthesis translate_on
end
assign k7_1000basex_pcs_pcsrx_timer_ce = k7_1000basex_pcs_pcsrx_decoder_ce;

// synthesis translate_off
reg dummy_d_6;
// synthesis translate_on
always @(*) begin
	k7_1000basex_pcs_pcsrx_decoder_input_msb_first <= 10'd0;
	k7_1000basex_pcs_pcsrx_decoder_input_msb_first[0] <= k7_1000basex_pcs_pcsrx_decoder_input[9];
	k7_1000basex_pcs_pcsrx_decoder_input_msb_first[1] <= k7_1000basex_pcs_pcsrx_decoder_input[8];
	k7_1000basex_pcs_pcsrx_decoder_input_msb_first[2] <= k7_1000basex_pcs_pcsrx_decoder_input[7];
	k7_1000basex_pcs_pcsrx_decoder_input_msb_first[3] <= k7_1000basex_pcs_pcsrx_decoder_input[6];
	k7_1000basex_pcs_pcsrx_decoder_input_msb_first[4] <= k7_1000basex_pcs_pcsrx_decoder_input[5];
	k7_1000basex_pcs_pcsrx_decoder_input_msb_first[5] <= k7_1000basex_pcs_pcsrx_decoder_input[4];
	k7_1000basex_pcs_pcsrx_decoder_input_msb_first[6] <= k7_1000basex_pcs_pcsrx_decoder_input[3];
	k7_1000basex_pcs_pcsrx_decoder_input_msb_first[7] <= k7_1000basex_pcs_pcsrx_decoder_input[2];
	k7_1000basex_pcs_pcsrx_decoder_input_msb_first[8] <= k7_1000basex_pcs_pcsrx_decoder_input[1];
	k7_1000basex_pcs_pcsrx_decoder_input_msb_first[9] <= k7_1000basex_pcs_pcsrx_decoder_input[0];
// synthesis translate_off
	dummy_d_6 <= dummy_s;
// synthesis translate_on
end
assign k7_1000basex_pcs_pcsrx_decoder_adr = k7_1000basex_pcs_pcsrx_decoder_input_msb_first[9:4];
assign k7_1000basex_pcs_pcsrx_decoder_re = k7_1000basex_pcs_pcsrx_decoder_ce;
assign k7_1000basex_pcs_pcsrx_decoder_code5b = k7_1000basex_pcs_pcsrx_decoder_dat_r;
assign k7_1000basex_pcs_pcsrx_decoder_d = {k7_1000basex_pcs_pcsrx_decoder_code3b, k7_1000basex_pcs_pcsrx_decoder_code5b};
assign k7_1000basex_pcs_pcsrx_decoder_invalid = (((k7_1000basex_pcs_pcsrx_decoder_ones != 3'd4) & (k7_1000basex_pcs_pcsrx_decoder_ones != 3'd5)) & (k7_1000basex_pcs_pcsrx_decoder_ones != 3'd6));
assign k7_1000basex_pcs_pcsrx_done = (k7_1000basex_pcs_pcsrx_count1 == 1'd0);
assign k7_1000basex_pcs_pcsrx_pipe_valid_sink_ready = ((~k7_1000basex_pcs_pcsrx_pipe_valid_source_valid) | k7_1000basex_pcs_pcsrx_pipe_valid_source_ready);
assign k7_1000basex_pcs_pcsrx_pipe_valid_sink_valid = k7_1000basex_pcs_pcsrx_sink_sink_valid;
assign k7_1000basex_pcs_pcsrx_sink_sink_ready = k7_1000basex_pcs_pcsrx_pipe_valid_sink_ready;
assign k7_1000basex_pcs_pcsrx_pipe_valid_sink_first = k7_1000basex_pcs_pcsrx_sink_sink_first;
assign k7_1000basex_pcs_pcsrx_pipe_valid_sink_last = k7_1000basex_pcs_pcsrx_sink_sink_last;
assign k7_1000basex_pcs_pcsrx_pipe_valid_sink_payload_data = k7_1000basex_pcs_pcsrx_sink_sink_payload_data;
assign k7_1000basex_pcs_pcsrx_source_source_valid = k7_1000basex_pcs_pcsrx_pipe_valid_source_valid;
assign k7_1000basex_pcs_pcsrx_pipe_valid_source_ready = k7_1000basex_pcs_pcsrx_source_source_ready;
assign k7_1000basex_pcs_pcsrx_source_source_first = k7_1000basex_pcs_pcsrx_pipe_valid_source_first;
assign k7_1000basex_pcs_pcsrx_source_source_last = k7_1000basex_pcs_pcsrx_pipe_valid_source_last;
assign k7_1000basex_pcs_pcsrx_source_source_payload_data = k7_1000basex_pcs_pcsrx_pipe_valid_source_payload_data;

// synthesis translate_off
reg dummy_d_7;
// synthesis translate_on
always @(*) begin
	k7_1000basex_pcs_pcsrx_seen_valid_ci <= 1'd0;
	k7_1000basex_pcs_pcsrx_seen_config_reg <= 1'd0;
	k7_1000basex_pcs_pcsrx_source_valid <= 1'd0;
	k7_1000basex_pcs_pcsrx_source_first <= 1'd0;
	k7_1000basex_pcs_pcsrx_source_last <= 1'd0;
	k7_1000basex_pcs_pcsrx_source_payload_data <= 8'd0;
	k7_1000basex_pcs_pcsrx_source_payload_error <= 1'd0;
	k7_1000basex_pcs_pcsrx_enable <= 1'd0;
	k7_1000basex_pcs_pcsrx_sink_sink_valid <= 1'd0;
	k7_1000basex_pcs_pcsrx_sink_sink_payload_data <= 8'd0;
	k7_1000basex_pcs_pcsrx_source_source_ready <= 1'd0;
	clockdomainsrenamer1_next_state <= 3'd0;
	k7_1000basex_pcs_pcsrx_count0_clockdomainsrenamer1_next_value <= 1'd0;
	k7_1000basex_pcs_pcsrx_count0_clockdomainsrenamer1_next_value_ce <= 1'd0;
	clockdomainsrenamer1_next_value0 <= 8'd0;
	clockdomainsrenamer1_next_value_ce0 <= 1'd0;
	clockdomainsrenamer1_next_value1 <= 8'd0;
	clockdomainsrenamer1_next_value_ce1 <= 1'd0;
	if ((k7_1000basex_pcs_pcsrx_timer_ce & k7_1000basex_pcs_pcsrx_done)) begin
		k7_1000basex_pcs_pcsrx_source_valid <= k7_1000basex_pcs_pcsrx_source_source_valid;
		k7_1000basex_pcs_pcsrx_source_source_ready <= k7_1000basex_pcs_pcsrx_source_ready;
		k7_1000basex_pcs_pcsrx_source_first <= k7_1000basex_pcs_pcsrx_source_source_first;
		k7_1000basex_pcs_pcsrx_source_payload_data <= k7_1000basex_pcs_pcsrx_source_source_payload_data;
		k7_1000basex_pcs_pcsrx_source_last <= (k7_1000basex_pcs_pcsrx_source_source_valid & (~k7_1000basex_pcs_pcsrx_sink_sink_valid));
	end
	clockdomainsrenamer1_next_state <= clockdomainsrenamer1_state;
	case (clockdomainsrenamer1_state)
		1'd1: begin
			if (k7_1000basex_pcs_pcsrx_decoder_ce) begin
				if (((~k7_1000basex_pcs_pcsrx_decoder_k) & (~k7_1000basex_pcs_pcsrx_decoder_invalid))) begin
					if (((k7_1000basex_pcs_pcsrx_decoder_d == 8'd181) | (k7_1000basex_pcs_pcsrx_decoder_d == 7'd66))) begin
						k7_1000basex_pcs_pcsrx_seen_valid_ci <= 1'd1;
						clockdomainsrenamer1_next_state <= 2'd2;
					end
					if (((k7_1000basex_pcs_pcsrx_decoder_d == 8'd197) | (k7_1000basex_pcs_pcsrx_decoder_d == 7'd80))) begin
						k7_1000basex_pcs_pcsrx_seen_valid_ci <= 1'd1;
						clockdomainsrenamer1_next_state <= 1'd0;
					end
				end else begin
					clockdomainsrenamer1_next_state <= 3'd4;
				end
			end
		end
		2'd2: begin
			if (k7_1000basex_pcs_pcsrx_decoder_ce) begin
				if (((~k7_1000basex_pcs_pcsrx_decoder_k) & (~k7_1000basex_pcs_pcsrx_decoder_invalid))) begin
					k7_1000basex_pcs_pcsrx_count0_clockdomainsrenamer1_next_value <= (k7_1000basex_pcs_pcsrx_count0 + 1'd1);
					k7_1000basex_pcs_pcsrx_count0_clockdomainsrenamer1_next_value_ce <= 1'd1;
					case (k7_1000basex_pcs_pcsrx_count0)
						1'd0: begin
							clockdomainsrenamer1_next_value0 <= k7_1000basex_pcs_pcsrx_decoder_d;
							clockdomainsrenamer1_next_value_ce0 <= 1'd1;
						end
						1'd1: begin
							clockdomainsrenamer1_next_value1 <= k7_1000basex_pcs_pcsrx_decoder_d;
							clockdomainsrenamer1_next_value_ce1 <= 1'd1;
						end
					endcase
					if ((k7_1000basex_pcs_pcsrx_count0 == 1'd1)) begin
						k7_1000basex_pcs_pcsrx_seen_config_reg <= 1'd1;
						clockdomainsrenamer1_next_state <= 1'd0;
					end
				end else begin
					clockdomainsrenamer1_next_state <= 3'd4;
				end
			end
		end
		2'd3: begin
			if (k7_1000basex_pcs_pcsrx_decoder_ce) begin
				if (((~k7_1000basex_pcs_pcsrx_decoder_k) & (~k7_1000basex_pcs_pcsrx_decoder_invalid))) begin
					k7_1000basex_pcs_pcsrx_enable <= 1'd1;
					k7_1000basex_pcs_pcsrx_sink_sink_valid <= k7_1000basex_pcs_pcsrx_done;
					k7_1000basex_pcs_pcsrx_sink_sink_payload_data <= k7_1000basex_pcs_pcsrx_decoder_d;
				end else begin
					if (((k7_1000basex_pcs_pcsrx_decoder_k & (k7_1000basex_pcs_pcsrx_decoder_d == 8'd253)) & (~k7_1000basex_pcs_pcsrx_decoder_invalid))) begin
						clockdomainsrenamer1_next_state <= 1'd0;
					end else begin
						k7_1000basex_pcs_pcsrx_source_payload_error <= 1'd1;
						k7_1000basex_pcs_pcsrx_source_last <= 1'd1;
						k7_1000basex_pcs_pcsrx_source_valid <= 1'd1;
						if (k7_1000basex_pcs_pcsrx_source_ready) begin
							clockdomainsrenamer1_next_state <= 3'd4;
						end
					end
				end
			end
		end
		3'd4: begin
			clockdomainsrenamer1_next_state <= 1'd0;
		end
		default: begin
			if (k7_1000basex_pcs_pcsrx_decoder_ce) begin
				if (k7_1000basex_pcs_pcsrx_decoder_k) begin
					if ((k7_1000basex_pcs_pcsrx_decoder_d == 8'd188)) begin
						k7_1000basex_pcs_pcsrx_count0_clockdomainsrenamer1_next_value <= 1'd0;
						k7_1000basex_pcs_pcsrx_count0_clockdomainsrenamer1_next_value_ce <= 1'd1;
						clockdomainsrenamer1_next_state <= 1'd1;
					end
					if ((k7_1000basex_pcs_pcsrx_decoder_d == 8'd251)) begin
						k7_1000basex_pcs_pcsrx_enable <= 1'd1;
						k7_1000basex_pcs_pcsrx_sink_sink_valid <= 1'd1;
						k7_1000basex_pcs_pcsrx_sink_sink_payload_data <= 7'd85;
						clockdomainsrenamer1_next_state <= 2'd3;
					end
				end
			end
		end
	endcase
// synthesis translate_off
	dummy_d_7 <= dummy_s;
// synthesis translate_on
end
assign k7_1000basex_pcs_lp_abi_wait = (~k7_1000basex_pcs_lp_abi_ping_i);
assign k7_1000basex_pcs_lp_abi_ping_i = ((k7_1000basex_pcs_lp_abi_starter | k7_1000basex_pcs_lp_abi_pong_o) | k7_1000basex_pcs_lp_abi_done);
assign k7_1000basex_pcs_lp_abi_pong_i = k7_1000basex_pcs_lp_abi_ping_o1;
assign k7_1000basex_pcs_lp_abi_ping_o0 = (k7_1000basex_pcs_lp_abi_ping_toggle_o ^ k7_1000basex_pcs_lp_abi_ping_toggle_o_r);
assign k7_1000basex_pcs_lp_abi_pong_o = (k7_1000basex_pcs_lp_abi_pong_toggle_o ^ k7_1000basex_pcs_lp_abi_pong_toggle_o_r);
assign k7_1000basex_pcs_lp_abi_done = (k7_1000basex_pcs_lp_abi_count == 1'd0);
assign k7_1000basex_pcs_seen_valid_ci_o = (k7_1000basex_pcs_seen_valid_ci_toggle_o ^ k7_1000basex_pcs_seen_valid_ci_toggle_o_r);
assign k7_1000basex_pcs_rx_config_reg_abi_o = (k7_1000basex_pcs_rx_config_reg_abi_toggle_o ^ k7_1000basex_pcs_rx_config_reg_abi_toggle_o_r);
assign k7_1000basex_pcs_rx_config_reg_ack_o = (k7_1000basex_pcs_rx_config_reg_ack_toggle_o ^ k7_1000basex_pcs_rx_config_reg_ack_toggle_o_r);
assign k7_1000basex_pcs_waittimer0_done = (k7_1000basex_pcs_waittimer0_count == 1'd0);
assign k7_1000basex_pcs_waittimer1_done = (k7_1000basex_pcs_waittimer1_count == 1'd0);
assign k7_1000basex_pcs_waittimer2_done = (k7_1000basex_pcs_waittimer2_count == 1'd0);

// synthesis translate_off
reg dummy_d_8;
// synthesis translate_on
always @(*) begin
	k7_1000basex_pcs_pcstx_config_valid <= 1'd0;
	k7_1000basex_pcs_link_up <= 1'd0;
	k7_1000basex_pcs_restart <= 1'd0;
	k7_1000basex_pcs_align <= 1'd0;
	k7_1000basex_pcs_config_empty <= 1'd0;
	k7_1000basex_pcs_autoneg_ack <= 1'd0;
	k7_1000basex_pcs_waittimer0_wait <= 1'd0;
	k7_1000basex_pcs_waittimer1_wait <= 1'd0;
	k7_1000basex_pcs_waittimer2_wait <= 1'd0;
	clockdomainsrenamer2_next_state <= 3'd0;
	clockdomainsrenamer2_next_state <= clockdomainsrenamer2_state;
	case (clockdomainsrenamer2_state)
		1'd1: begin
			k7_1000basex_pcs_align <= 1'd1;
			k7_1000basex_pcs_pcstx_config_valid <= 1'd1;
			if (k7_1000basex_pcs_rx_config_reg_abi_o) begin
				clockdomainsrenamer2_next_state <= 2'd2;
			end
			if ((k7_1000basex_pcs_checker_tick & k7_1000basex_pcs_checker_error)) begin
				k7_1000basex_pcs_restart <= 1'd1;
				clockdomainsrenamer2_next_state <= 1'd0;
			end
		end
		2'd2: begin
			k7_1000basex_pcs_pcstx_config_valid <= 1'd1;
			k7_1000basex_pcs_autoneg_ack <= 1'd1;
			if (k7_1000basex_pcs_rx_config_reg_ack_o) begin
				clockdomainsrenamer2_next_state <= 2'd3;
			end
			if ((k7_1000basex_pcs_checker_tick & k7_1000basex_pcs_checker_error)) begin
				k7_1000basex_pcs_restart <= 1'd1;
				clockdomainsrenamer2_next_state <= 1'd0;
			end
		end
		2'd3: begin
			k7_1000basex_pcs_pcstx_config_valid <= 1'd1;
			k7_1000basex_pcs_autoneg_ack <= 1'd1;
			k7_1000basex_pcs_waittimer1_wait <= (~k7_1000basex_pcs_is_sgmii);
			k7_1000basex_pcs_waittimer2_wait <= k7_1000basex_pcs_is_sgmii;
			if (((k7_1000basex_pcs_is_sgmii & k7_1000basex_pcs_waittimer2_done) | ((~k7_1000basex_pcs_is_sgmii) & k7_1000basex_pcs_waittimer1_done))) begin
				clockdomainsrenamer2_next_state <= 3'd4;
			end
			if ((k7_1000basex_pcs_checker_tick & k7_1000basex_pcs_checker_error)) begin
				k7_1000basex_pcs_restart <= 1'd1;
				clockdomainsrenamer2_next_state <= 1'd0;
			end
		end
		3'd4: begin
			k7_1000basex_pcs_link_up <= (~k7_1000basex_pcs_linkdown);
			if (((k7_1000basex_pcs_checker_tick & k7_1000basex_pcs_checker_error) | k7_1000basex_pcs_linkdown)) begin
				k7_1000basex_pcs_restart <= 1'd1;
				clockdomainsrenamer2_next_state <= 1'd0;
			end
		end
		default: begin
			k7_1000basex_pcs_pcstx_config_valid <= 1'd1;
			k7_1000basex_pcs_config_empty <= 1'd1;
			k7_1000basex_pcs_waittimer0_wait <= 1'd1;
			if (k7_1000basex_pcs_waittimer0_done) begin
				clockdomainsrenamer2_next_state <= 1'd1;
			end
		end
	endcase
// synthesis translate_off
	dummy_d_8 <= dummy_s;
// synthesis translate_on
end
assign k7_1000basex_s7mmcm0_clkin_signal = k7_1000basex_txoutclk_rebuffer;
assign eth_tx_half_clk = k7_1000basex_s7mmcm0_clkout_buf0;
assign eth_tx_clk = k7_1000basex_s7mmcm0_clkout_buf1;
assign k7_1000basex_s7mmcm1_clkin_signal = k7_1000basex_rxoutclk_rebuffer;
assign eth_rx_half_clk = k7_1000basex_s7mmcm1_clkout_buf0;
assign eth_rx_clk = k7_1000basex_s7mmcm1_clkout_buf1;
assign k7_1000basex_gtxtxinit_Xxphaligndone_rising = (k7_1000basex_gtxtxinit_Xxphaligndone1 & (~k7_1000basex_gtxtxinit_Xxphaligndone_r));
assign k7_1000basex_gtxtxinit_init_delay_wait = 1'd1;
assign k7_1000basex_gtxtxinit_watchdog_wait = ((~k7_1000basex_gtxtxinit_reset) & (~k7_1000basex_gtxtxinit_done));
assign k7_1000basex_gtxtxinit_reset = (k7_1000basex_gtxtxinit_restart | k7_1000basex_gtxtxinit_watchdog_done);

// synthesis translate_off
reg dummy_d_9;
// synthesis translate_on
always @(*) begin
	k7_1000basex_gtxtxinit_done <= 1'd0;
	k7_1000basex_gtxtxinit_drp_start <= 1'd0;
	k7_1000basex_gtxtxinit_pllreset1 <= 1'd0;
	k7_1000basex_gtxtxinit_gtXxreset1 <= 1'd0;
	k7_1000basex_gtxtxinit_gtXxpd1 <= 1'd0;
	k7_1000basex_gtxtxinit_Xxdlysreset1 <= 1'd0;
	k7_1000basex_gtxtxinit_Xxuserrdy1 <= 1'd0;
	k7_1000basex_gtxtxinit_cdr_lock_timer_wait <= 1'd0;
	gtxtxinit_next_state <= 4'd0;
	gtxtxinit_next_state <= gtxtxinit_state;
	case (gtxtxinit_state)
		1'd1: begin
			k7_1000basex_gtxtxinit_gtXxreset1 <= 1'd1;
			k7_1000basex_gtxtxinit_pllreset1 <= 1'd1;
			k7_1000basex_gtxtxinit_drp_start <= 1'd1;
			if (k7_1000basex_gtxtxinit_drp_done) begin
				gtxtxinit_next_state <= 2'd2;
			end
		end
		2'd2: begin
			k7_1000basex_gtxtxinit_gtXxreset1 <= 1'd1;
			if (k7_1000basex_gtxtxinit_plllock1) begin
				gtxtxinit_next_state <= 2'd3;
			end
		end
		2'd3: begin
			k7_1000basex_gtxtxinit_gtXxreset1 <= 1'd1;
			if (k7_1000basex_gtxtxinit_init_delay_done) begin
				gtxtxinit_next_state <= 3'd4;
			end
		end
		3'd4: begin
			k7_1000basex_gtxtxinit_Xxuserrdy1 <= 1'd1;
			if (k7_1000basex_gtxtxinit_Xxresetdone1) begin
				gtxtxinit_next_state <= 3'd5;
			end
		end
		3'd5: begin
			k7_1000basex_gtxtxinit_Xxuserrdy1 <= 1'd1;
			k7_1000basex_gtxtxinit_cdr_lock_timer_wait <= 1'd1;
			if (k7_1000basex_gtxtxinit_cdr_lock_timer_done) begin
				if (1'd1) begin
					gtxtxinit_next_state <= 4'd10;
				end else begin
					gtxtxinit_next_state <= 3'd6;
				end
			end
		end
		3'd6: begin
			k7_1000basex_gtxtxinit_Xxuserrdy1 <= 1'd1;
			k7_1000basex_gtxtxinit_Xxdlysreset1 <= 1'd1;
			gtxtxinit_next_state <= 3'd7;
		end
		3'd7: begin
			k7_1000basex_gtxtxinit_Xxuserrdy1 <= 1'd1;
			if (k7_1000basex_gtxtxinit_Xxdlysresetdone1) begin
				gtxtxinit_next_state <= 4'd8;
			end
		end
		4'd8: begin
			k7_1000basex_gtxtxinit_Xxuserrdy1 <= 1'd1;
			if (k7_1000basex_gtxtxinit_Xxphaligndone_rising) begin
				gtxtxinit_next_state <= 4'd9;
			end
		end
		4'd9: begin
			k7_1000basex_gtxtxinit_Xxuserrdy1 <= 1'd1;
			if (k7_1000basex_gtxtxinit_Xxphaligndone_rising) begin
				gtxtxinit_next_state <= 4'd10;
			end
		end
		4'd10: begin
			k7_1000basex_gtxtxinit_Xxuserrdy1 <= 1'd1;
			k7_1000basex_gtxtxinit_done <= 1'd1;
			if (k7_1000basex_gtxtxinit_restart) begin
				gtxtxinit_next_state <= 1'd0;
			end
		end
		default: begin
			k7_1000basex_gtxtxinit_gtXxreset1 <= 1'd1;
			k7_1000basex_gtxtxinit_gtXxpd1 <= 1'd1;
			k7_1000basex_gtxtxinit_pllreset1 <= 1'd1;
			gtxtxinit_next_state <= 1'd1;
		end
	endcase
// synthesis translate_off
	dummy_d_9 <= dummy_s;
// synthesis translate_on
end
assign k7_1000basex_gtxtxinit_init_delay_done = (k7_1000basex_gtxtxinit_init_delay_count == 1'd0);
assign k7_1000basex_gtxtxinit_cdr_lock_timer_done = (k7_1000basex_gtxtxinit_cdr_lock_timer_count == 1'd0);
assign k7_1000basex_gtxtxinit_watchdog_done = (k7_1000basex_gtxtxinit_watchdog_count == 1'd0);
assign k7_1000basex_gtxrxinit_Xxphaligndone_rising = (k7_1000basex_gtxrxinit_Xxphaligndone1 & (~k7_1000basex_gtxrxinit_Xxphaligndone_r));
assign k7_1000basex_gtxrxinit_init_delay_wait = 1'd1;
assign k7_1000basex_gtxrxinit_watchdog_wait = ((~k7_1000basex_gtxrxinit_reset) & (~k7_1000basex_gtxrxinit_done));
assign k7_1000basex_gtxrxinit_reset = (k7_1000basex_gtxrxinit_restart | k7_1000basex_gtxrxinit_watchdog_done);

// synthesis translate_off
reg dummy_d_10;
// synthesis translate_on
always @(*) begin
	k7_1000basex_gtxrxinit_done <= 1'd0;
	k7_1000basex_gtxrxinit_drp_start <= 1'd0;
	k7_1000basex_gtxrxinit_pllreset1 <= 1'd0;
	k7_1000basex_gtxrxinit_gtXxreset1 <= 1'd0;
	k7_1000basex_gtxrxinit_gtXxpd1 <= 1'd0;
	k7_1000basex_gtxrxinit_Xxdlysreset1 <= 1'd0;
	k7_1000basex_gtxrxinit_Xxuserrdy1 <= 1'd0;
	k7_1000basex_gtxrxinit_cdr_lock_timer_wait <= 1'd0;
	gtxrxinit_next_state <= 4'd0;
	gtxrxinit_next_state <= gtxrxinit_state;
	case (gtxrxinit_state)
		1'd1: begin
			k7_1000basex_gtxrxinit_gtXxreset1 <= 1'd1;
			k7_1000basex_gtxrxinit_pllreset1 <= 1'd1;
			k7_1000basex_gtxrxinit_drp_start <= 1'd1;
			if (k7_1000basex_gtxrxinit_drp_done) begin
				gtxrxinit_next_state <= 2'd2;
			end
		end
		2'd2: begin
			k7_1000basex_gtxrxinit_gtXxreset1 <= 1'd1;
			if (k7_1000basex_gtxrxinit_plllock1) begin
				gtxrxinit_next_state <= 2'd3;
			end
		end
		2'd3: begin
			k7_1000basex_gtxrxinit_gtXxreset1 <= 1'd1;
			if (k7_1000basex_gtxrxinit_init_delay_done) begin
				gtxrxinit_next_state <= 3'd4;
			end
		end
		3'd4: begin
			k7_1000basex_gtxrxinit_Xxuserrdy1 <= 1'd1;
			if (k7_1000basex_gtxrxinit_Xxresetdone1) begin
				gtxrxinit_next_state <= 3'd5;
			end
		end
		3'd5: begin
			k7_1000basex_gtxrxinit_Xxuserrdy1 <= 1'd1;
			k7_1000basex_gtxrxinit_cdr_lock_timer_wait <= 1'd1;
			if (k7_1000basex_gtxrxinit_cdr_lock_timer_done) begin
				if (1'd1) begin
					gtxrxinit_next_state <= 4'd10;
				end else begin
					gtxrxinit_next_state <= 3'd6;
				end
			end
		end
		3'd6: begin
			k7_1000basex_gtxrxinit_Xxuserrdy1 <= 1'd1;
			k7_1000basex_gtxrxinit_Xxdlysreset1 <= 1'd1;
			gtxrxinit_next_state <= 3'd7;
		end
		3'd7: begin
			k7_1000basex_gtxrxinit_Xxuserrdy1 <= 1'd1;
			if (k7_1000basex_gtxrxinit_Xxdlysresetdone1) begin
				gtxrxinit_next_state <= 4'd8;
			end
		end
		4'd8: begin
			k7_1000basex_gtxrxinit_Xxuserrdy1 <= 1'd1;
			if (k7_1000basex_gtxrxinit_Xxphaligndone_rising) begin
				gtxrxinit_next_state <= 4'd9;
			end
		end
		4'd9: begin
			k7_1000basex_gtxrxinit_Xxuserrdy1 <= 1'd1;
			if (k7_1000basex_gtxrxinit_Xxphaligndone_rising) begin
				gtxrxinit_next_state <= 4'd10;
			end
		end
		4'd10: begin
			k7_1000basex_gtxrxinit_Xxuserrdy1 <= 1'd1;
			k7_1000basex_gtxrxinit_done <= 1'd1;
			if (k7_1000basex_gtxrxinit_restart) begin
				gtxrxinit_next_state <= 1'd0;
			end
		end
		default: begin
			k7_1000basex_gtxrxinit_gtXxreset1 <= 1'd1;
			k7_1000basex_gtxrxinit_gtXxpd1 <= 1'd1;
			k7_1000basex_gtxrxinit_pllreset1 <= 1'd1;
			gtxrxinit_next_state <= 1'd1;
		end
	endcase
// synthesis translate_off
	dummy_d_10 <= dummy_s;
// synthesis translate_on
end
assign k7_1000basex_gtxrxinit_init_delay_done = (k7_1000basex_gtxrxinit_init_delay_count == 1'd0);
assign k7_1000basex_gtxrxinit_cdr_lock_timer_done = (k7_1000basex_gtxrxinit_cdr_lock_timer_count == 1'd0);
assign k7_1000basex_gtxrxinit_watchdog_done = (k7_1000basex_gtxrxinit_watchdog_count == 1'd0);
assign k7_1000basex_o = (k7_1000basex_toggle_o ^ k7_1000basex_toggle_o_r);

// synthesis translate_off
reg dummy_d_11;
// synthesis translate_on
always @(*) begin
	t_self0 <= 3'd0;
	case (k7_1000basex_pcs_pcsrx_decoder_input_msb_first[3:0])
		1'd0: begin
			t_self0 <= 1'd0;
		end
		1'd1: begin
			t_self0 <= 1'd0;
		end
		2'd2: begin
			t_self0 <= 3'd4;
		end
		2'd3: begin
			t_self0 <= 2'd3;
		end
		3'd4: begin
			t_self0 <= 1'd0;
		end
		3'd5: begin
			t_self0 <= 2'd2;
		end
		3'd6: begin
			t_self0 <= 3'd6;
		end
		3'd7: begin
			t_self0 <= 1'd0;
		end
		4'd8: begin
			t_self0 <= 3'd7;
		end
		4'd9: begin
			t_self0 <= 1'd1;
		end
		4'd10: begin
			t_self0 <= 3'd5;
		end
		4'd11: begin
			t_self0 <= 1'd0;
		end
		4'd12: begin
			t_self0 <= 1'd0;
		end
		4'd13: begin
			t_self0 <= 1'd0;
		end
		4'd14: begin
			t_self0 <= 1'd0;
		end
		default: begin
			t_self0 <= 1'd0;
		end
	endcase
// synthesis translate_off
	dummy_d_11 <= dummy_s;
// synthesis translate_on
end

// synthesis translate_off
reg dummy_d_12;
// synthesis translate_on
always @(*) begin
	t_self1 <= 3'd0;
	case (k7_1000basex_pcs_pcsrx_decoder_input_msb_first[3:0])
		1'd0: begin
			t_self1 <= 1'd0;
		end
		1'd1: begin
			t_self1 <= 1'd0;
		end
		2'd2: begin
			t_self1 <= 1'd0;
		end
		2'd3: begin
			t_self1 <= 1'd0;
		end
		3'd4: begin
			t_self1 <= 1'd0;
		end
		3'd5: begin
			t_self1 <= 3'd5;
		end
		3'd6: begin
			t_self1 <= 1'd1;
		end
		3'd7: begin
			t_self1 <= 3'd7;
		end
		4'd8: begin
			t_self1 <= 1'd0;
		end
		4'd9: begin
			t_self1 <= 3'd6;
		end
		4'd10: begin
			t_self1 <= 2'd2;
		end
		4'd11: begin
			t_self1 <= 1'd0;
		end
		4'd12: begin
			t_self1 <= 2'd3;
		end
		4'd13: begin
			t_self1 <= 3'd4;
		end
		4'd14: begin
			t_self1 <= 1'd0;
		end
		default: begin
			t_self1 <= 1'd0;
		end
	endcase
// synthesis translate_off
	dummy_d_12 <= dummy_s;
// synthesis translate_on
end

// synthesis translate_off
reg dummy_d_13;
// synthesis translate_on
always @(*) begin
	f_self <= 3'd0;
	case (k7_1000basex_pcs_pcsrx_decoder_input_msb_first[3:0])
		1'd0: begin
			f_self <= 1'd0;
		end
		1'd1: begin
			f_self <= 3'd7;
		end
		2'd2: begin
			f_self <= 3'd4;
		end
		2'd3: begin
			f_self <= 2'd3;
		end
		3'd4: begin
			f_self <= 1'd0;
		end
		3'd5: begin
			f_self <= 2'd2;
		end
		3'd6: begin
			f_self <= 3'd6;
		end
		3'd7: begin
			f_self <= 3'd7;
		end
		4'd8: begin
			f_self <= 3'd7;
		end
		4'd9: begin
			f_self <= 1'd1;
		end
		4'd10: begin
			f_self <= 3'd5;
		end
		4'd11: begin
			f_self <= 1'd0;
		end
		4'd12: begin
			f_self <= 2'd3;
		end
		4'd13: begin
			f_self <= 3'd4;
		end
		4'd14: begin
			f_self <= 3'd7;
		end
		default: begin
			f_self <= 1'd0;
		end
	endcase
// synthesis translate_off
	dummy_d_13 <= dummy_s;
// synthesis translate_on
end

// synthesis translate_off
reg dummy_d_14;
// synthesis translate_on
always @(*) begin
	rhs_self0 <= 6'd0;
	case (k7_1000basex_pcs_pcstx_encoder_d[4:0])
		1'd0: begin
			rhs_self0 <= 5'd24;
		end
		1'd1: begin
			rhs_self0 <= 6'd34;
		end
		2'd2: begin
			rhs_self0 <= 5'd18;
		end
		2'd3: begin
			rhs_self0 <= 6'd49;
		end
		3'd4: begin
			rhs_self0 <= 4'd10;
		end
		3'd5: begin
			rhs_self0 <= 6'd41;
		end
		3'd6: begin
			rhs_self0 <= 5'd25;
		end
		3'd7: begin
			rhs_self0 <= 3'd7;
		end
		4'd8: begin
			rhs_self0 <= 3'd6;
		end
		4'd9: begin
			rhs_self0 <= 6'd37;
		end
		4'd10: begin
			rhs_self0 <= 5'd21;
		end
		4'd11: begin
			rhs_self0 <= 6'd52;
		end
		4'd12: begin
			rhs_self0 <= 4'd13;
		end
		4'd13: begin
			rhs_self0 <= 6'd44;
		end
		4'd14: begin
			rhs_self0 <= 5'd28;
		end
		4'd15: begin
			rhs_self0 <= 6'd40;
		end
		5'd16: begin
			rhs_self0 <= 6'd36;
		end
		5'd17: begin
			rhs_self0 <= 6'd35;
		end
		5'd18: begin
			rhs_self0 <= 5'd19;
		end
		5'd19: begin
			rhs_self0 <= 6'd50;
		end
		5'd20: begin
			rhs_self0 <= 4'd11;
		end
		5'd21: begin
			rhs_self0 <= 6'd42;
		end
		5'd22: begin
			rhs_self0 <= 5'd26;
		end
		5'd23: begin
			rhs_self0 <= 3'd5;
		end
		5'd24: begin
			rhs_self0 <= 4'd12;
		end
		5'd25: begin
			rhs_self0 <= 6'd38;
		end
		5'd26: begin
			rhs_self0 <= 5'd22;
		end
		5'd27: begin
			rhs_self0 <= 4'd9;
		end
		5'd28: begin
			rhs_self0 <= 4'd14;
		end
		5'd29: begin
			rhs_self0 <= 5'd17;
		end
		5'd30: begin
			rhs_self0 <= 6'd33;
		end
		default: begin
			rhs_self0 <= 5'd20;
		end
	endcase
// synthesis translate_off
	dummy_d_14 <= dummy_s;
// synthesis translate_on
end

// synthesis translate_off
reg dummy_d_15;
// synthesis translate_on
always @(*) begin
	rhs_self1 <= 1'd0;
	case (k7_1000basex_pcs_pcstx_encoder_d[4:0])
		1'd0: begin
			rhs_self1 <= 1'd1;
		end
		1'd1: begin
			rhs_self1 <= 1'd1;
		end
		2'd2: begin
			rhs_self1 <= 1'd1;
		end
		2'd3: begin
			rhs_self1 <= 1'd0;
		end
		3'd4: begin
			rhs_self1 <= 1'd1;
		end
		3'd5: begin
			rhs_self1 <= 1'd0;
		end
		3'd6: begin
			rhs_self1 <= 1'd0;
		end
		3'd7: begin
			rhs_self1 <= 1'd0;
		end
		4'd8: begin
			rhs_self1 <= 1'd1;
		end
		4'd9: begin
			rhs_self1 <= 1'd0;
		end
		4'd10: begin
			rhs_self1 <= 1'd0;
		end
		4'd11: begin
			rhs_self1 <= 1'd0;
		end
		4'd12: begin
			rhs_self1 <= 1'd0;
		end
		4'd13: begin
			rhs_self1 <= 1'd0;
		end
		4'd14: begin
			rhs_self1 <= 1'd0;
		end
		4'd15: begin
			rhs_self1 <= 1'd1;
		end
		5'd16: begin
			rhs_self1 <= 1'd1;
		end
		5'd17: begin
			rhs_self1 <= 1'd0;
		end
		5'd18: begin
			rhs_self1 <= 1'd0;
		end
		5'd19: begin
			rhs_self1 <= 1'd0;
		end
		5'd20: begin
			rhs_self1 <= 1'd0;
		end
		5'd21: begin
			rhs_self1 <= 1'd0;
		end
		5'd22: begin
			rhs_self1 <= 1'd0;
		end
		5'd23: begin
			rhs_self1 <= 1'd1;
		end
		5'd24: begin
			rhs_self1 <= 1'd1;
		end
		5'd25: begin
			rhs_self1 <= 1'd0;
		end
		5'd26: begin
			rhs_self1 <= 1'd0;
		end
		5'd27: begin
			rhs_self1 <= 1'd1;
		end
		5'd28: begin
			rhs_self1 <= 1'd0;
		end
		5'd29: begin
			rhs_self1 <= 1'd1;
		end
		5'd30: begin
			rhs_self1 <= 1'd1;
		end
		default: begin
			rhs_self1 <= 1'd1;
		end
	endcase
// synthesis translate_off
	dummy_d_15 <= dummy_s;
// synthesis translate_on
end

// synthesis translate_off
reg dummy_d_16;
// synthesis translate_on
always @(*) begin
	rhs_self2 <= 1'd0;
	case (k7_1000basex_pcs_pcstx_encoder_d[4:0])
		1'd0: begin
			rhs_self2 <= 1'd1;
		end
		1'd1: begin
			rhs_self2 <= 1'd1;
		end
		2'd2: begin
			rhs_self2 <= 1'd1;
		end
		2'd3: begin
			rhs_self2 <= 1'd0;
		end
		3'd4: begin
			rhs_self2 <= 1'd1;
		end
		3'd5: begin
			rhs_self2 <= 1'd0;
		end
		3'd6: begin
			rhs_self2 <= 1'd0;
		end
		3'd7: begin
			rhs_self2 <= 1'd1;
		end
		4'd8: begin
			rhs_self2 <= 1'd1;
		end
		4'd9: begin
			rhs_self2 <= 1'd0;
		end
		4'd10: begin
			rhs_self2 <= 1'd0;
		end
		4'd11: begin
			rhs_self2 <= 1'd0;
		end
		4'd12: begin
			rhs_self2 <= 1'd0;
		end
		4'd13: begin
			rhs_self2 <= 1'd0;
		end
		4'd14: begin
			rhs_self2 <= 1'd0;
		end
		4'd15: begin
			rhs_self2 <= 1'd1;
		end
		5'd16: begin
			rhs_self2 <= 1'd1;
		end
		5'd17: begin
			rhs_self2 <= 1'd0;
		end
		5'd18: begin
			rhs_self2 <= 1'd0;
		end
		5'd19: begin
			rhs_self2 <= 1'd0;
		end
		5'd20: begin
			rhs_self2 <= 1'd0;
		end
		5'd21: begin
			rhs_self2 <= 1'd0;
		end
		5'd22: begin
			rhs_self2 <= 1'd0;
		end
		5'd23: begin
			rhs_self2 <= 1'd1;
		end
		5'd24: begin
			rhs_self2 <= 1'd1;
		end
		5'd25: begin
			rhs_self2 <= 1'd0;
		end
		5'd26: begin
			rhs_self2 <= 1'd0;
		end
		5'd27: begin
			rhs_self2 <= 1'd1;
		end
		5'd28: begin
			rhs_self2 <= 1'd0;
		end
		5'd29: begin
			rhs_self2 <= 1'd1;
		end
		5'd30: begin
			rhs_self2 <= 1'd1;
		end
		default: begin
			rhs_self2 <= 1'd1;
		end
	endcase
// synthesis translate_off
	dummy_d_16 <= dummy_s;
// synthesis translate_on
end

// synthesis translate_off
reg dummy_d_17;
// synthesis translate_on
always @(*) begin
	rhs_self3 <= 4'd0;
	case (k7_1000basex_pcs_pcstx_encoder_d[7:5])
		1'd0: begin
			rhs_self3 <= 3'd4;
		end
		1'd1: begin
			rhs_self3 <= 4'd9;
		end
		2'd2: begin
			rhs_self3 <= 3'd5;
		end
		2'd3: begin
			rhs_self3 <= 2'd3;
		end
		3'd4: begin
			rhs_self3 <= 2'd2;
		end
		3'd5: begin
			rhs_self3 <= 4'd10;
		end
		3'd6: begin
			rhs_self3 <= 3'd6;
		end
		default: begin
			rhs_self3 <= 1'd1;
		end
	endcase
// synthesis translate_off
	dummy_d_17 <= dummy_s;
// synthesis translate_on
end

// synthesis translate_off
reg dummy_d_18;
// synthesis translate_on
always @(*) begin
	rhs_self4 <= 1'd0;
	case (k7_1000basex_pcs_pcstx_encoder_d[7:5])
		1'd0: begin
			rhs_self4 <= 1'd1;
		end
		1'd1: begin
			rhs_self4 <= 1'd0;
		end
		2'd2: begin
			rhs_self4 <= 1'd0;
		end
		2'd3: begin
			rhs_self4 <= 1'd0;
		end
		3'd4: begin
			rhs_self4 <= 1'd1;
		end
		3'd5: begin
			rhs_self4 <= 1'd0;
		end
		3'd6: begin
			rhs_self4 <= 1'd0;
		end
		default: begin
			rhs_self4 <= 1'd1;
		end
	endcase
// synthesis translate_off
	dummy_d_18 <= dummy_s;
// synthesis translate_on
end

// synthesis translate_off
reg dummy_d_19;
// synthesis translate_on
always @(*) begin
	rhs_self5 <= 1'd0;
	case (k7_1000basex_pcs_pcstx_encoder_d[7:5])
		1'd0: begin
			rhs_self5 <= 1'd1;
		end
		1'd1: begin
			rhs_self5 <= 1'd0;
		end
		2'd2: begin
			rhs_self5 <= 1'd0;
		end
		2'd3: begin
			rhs_self5 <= 1'd1;
		end
		3'd4: begin
			rhs_self5 <= 1'd1;
		end
		3'd5: begin
			rhs_self5 <= 1'd0;
		end
		3'd6: begin
			rhs_self5 <= 1'd0;
		end
		default: begin
			rhs_self5 <= 1'd1;
		end
	endcase
// synthesis translate_off
	dummy_d_19 <= dummy_s;
// synthesis translate_on
end
assign k7_1000basex_pcs_lp_abi_ping_toggle_o = xilinxmultiregimpl01;
assign k7_1000basex_pcs_lp_abi_pong_toggle_o = xilinxmultiregimpl11;
assign k7_1000basex_pcs_lp_abi_obuffer = xilinxmultiregimpl21;
assign k7_1000basex_pcs_seen_valid_ci_toggle_o = xilinxmultiregimpl31;
assign k7_1000basex_pcs_rx_config_reg_abi_toggle_o = xilinxmultiregimpl41;
assign k7_1000basex_pcs_rx_config_reg_ack_toggle_o = xilinxmultiregimpl51;
assign xilinxasyncresetsynchronizerimpl0 = (~k7_1000basex_tx_mmcm_locked1);
assign xilinxasyncresetsynchronizerimpl1 = (~k7_1000basex_rx_mmcm_locked1);
assign k7_1000basex_gtxtxinit_plllock1 = xilinxmultiregimpl61;
assign k7_1000basex_gtxtxinit_Xxresetdone1 = xilinxmultiregimpl71;
assign k7_1000basex_gtxtxinit_Xxdlysresetdone1 = xilinxmultiregimpl81;
assign k7_1000basex_gtxtxinit_Xxphaligndone1 = xilinxmultiregimpl91;
assign k7_1000basex_gtxrxinit_plllock1 = xilinxmultiregimpl101;
assign k7_1000basex_gtxrxinit_Xxresetdone1 = xilinxmultiregimpl111;
assign k7_1000basex_gtxrxinit_Xxdlysresetdone1 = xilinxmultiregimpl121;
assign k7_1000basex_gtxrxinit_Xxphaligndone1 = xilinxmultiregimpl131;
assign k7_1000basex_toggle_o = xilinxmultiregimpl141;

always @(posedge eth_rx_clk) begin
	if (k7_1000basex_pcs_pcsrx_seen_config_reg) begin
		k7_1000basex_pcs_rx_config_reg_last <= k7_1000basex_pcs_pcsrx_config_reg;
		if ((k7_1000basex_pcs_pcsrx_config_reg != k7_1000basex_pcs_rx_config_reg_last)) begin
			k7_1000basex_pcs_rx_config_reg_count <= 3'd7;
		end else begin
			if ((k7_1000basex_pcs_rx_config_reg_count != 1'd0)) begin
				k7_1000basex_pcs_rx_config_reg_count <= (k7_1000basex_pcs_rx_config_reg_count - 1'd1);
			end else begin
				if (k7_1000basex_pcs_pcsrx_config_reg[14]) begin
					k7_1000basex_pcs_rx_config_reg_ack_i <= 1'd1;
				end else begin
					k7_1000basex_pcs_rx_config_reg_abi_i <= 1'd1;
				end
			end
		end
		k7_1000basex_pcs_lp_abi_i <= k7_1000basex_pcs_pcsrx_config_reg;
	end
	if (k7_1000basex_pcs_pcsrx_decoder_ce) begin
		k7_1000basex_pcs_pcsrx_decoder_k <= 1'd0;
		if ((k7_1000basex_pcs_pcsrx_decoder_input_msb_first[9:4] == 4'd15)) begin
			k7_1000basex_pcs_pcsrx_decoder_k <= 1'd1;
			k7_1000basex_pcs_pcsrx_decoder_code3b <= t_self0;
		end else begin
			if ((k7_1000basex_pcs_pcsrx_decoder_input_msb_first[9:4] == 6'd48)) begin
				k7_1000basex_pcs_pcsrx_decoder_k <= 1'd1;
				k7_1000basex_pcs_pcsrx_decoder_code3b <= t_self1;
			end else begin
				if (((k7_1000basex_pcs_pcsrx_decoder_input_msb_first[3:0] == 3'd7) | (k7_1000basex_pcs_pcsrx_decoder_input_msb_first[3:0] == 4'd8))) begin
					if (((((((k7_1000basex_pcs_pcsrx_decoder_input_msb_first[9:4] != 6'd35) & (k7_1000basex_pcs_pcsrx_decoder_input_msb_first[9:4] != 5'd19)) & (k7_1000basex_pcs_pcsrx_decoder_input_msb_first[9:4] != 4'd11)) & (k7_1000basex_pcs_pcsrx_decoder_input_msb_first[9:4] != 6'd52)) & (k7_1000basex_pcs_pcsrx_decoder_input_msb_first[9:4] != 6'd44)) & (k7_1000basex_pcs_pcsrx_decoder_input_msb_first[9:4] != 5'd28))) begin
						k7_1000basex_pcs_pcsrx_decoder_k <= 1'd1;
					end
				end
				k7_1000basex_pcs_pcsrx_decoder_code3b <= f_self;
			end
		end
	end
	if (k7_1000basex_pcs_pcsrx_decoder_ce) begin
		k7_1000basex_pcs_pcsrx_decoder_ones <= (((((((((k7_1000basex_pcs_pcsrx_decoder_input[0] + k7_1000basex_pcs_pcsrx_decoder_input[1]) + k7_1000basex_pcs_pcsrx_decoder_input[2]) + k7_1000basex_pcs_pcsrx_decoder_input[3]) + k7_1000basex_pcs_pcsrx_decoder_input[4]) + k7_1000basex_pcs_pcsrx_decoder_input[5]) + k7_1000basex_pcs_pcsrx_decoder_input[6]) + k7_1000basex_pcs_pcsrx_decoder_input[7]) + k7_1000basex_pcs_pcsrx_decoder_input[8]) + k7_1000basex_pcs_pcsrx_decoder_input[9]);
	end
	if (k7_1000basex_pcs_pcsrx_timer_ce) begin
		k7_1000basex_pcs_pcsrx_count1 <= (k7_1000basex_pcs_pcsrx_count1 - 1'd1);
		if (((~k7_1000basex_pcs_pcsrx_enable) | k7_1000basex_pcs_pcsrx_done)) begin
			case (k7_1000basex_pcs_pcsrx_sgmii_speed)
				1'd0: begin
					k7_1000basex_pcs_pcsrx_count1 <= 7'd99;
				end
				1'd1: begin
					k7_1000basex_pcs_pcsrx_count1 <= 4'd9;
				end
				2'd2: begin
					k7_1000basex_pcs_pcsrx_count1 <= 1'd0;
				end
			endcase
		end
	end
	if (((~k7_1000basex_pcs_pcsrx_pipe_valid_source_valid) | k7_1000basex_pcs_pcsrx_pipe_valid_source_ready)) begin
		k7_1000basex_pcs_pcsrx_pipe_valid_source_valid <= k7_1000basex_pcs_pcsrx_pipe_valid_sink_valid;
		k7_1000basex_pcs_pcsrx_pipe_valid_source_first <= k7_1000basex_pcs_pcsrx_pipe_valid_sink_first;
		k7_1000basex_pcs_pcsrx_pipe_valid_source_last <= k7_1000basex_pcs_pcsrx_pipe_valid_sink_last;
		k7_1000basex_pcs_pcsrx_pipe_valid_source_payload_data <= k7_1000basex_pcs_pcsrx_pipe_valid_sink_payload_data;
	end
	clockdomainsrenamer1_state <= clockdomainsrenamer1_next_state;
	if (k7_1000basex_pcs_pcsrx_count0_clockdomainsrenamer1_next_value_ce) begin
		k7_1000basex_pcs_pcsrx_count0 <= k7_1000basex_pcs_pcsrx_count0_clockdomainsrenamer1_next_value;
	end
	if (clockdomainsrenamer1_next_value_ce0) begin
		k7_1000basex_pcs_pcsrx_config_reg[7:0] <= clockdomainsrenamer1_next_value0;
	end
	if (clockdomainsrenamer1_next_value_ce1) begin
		k7_1000basex_pcs_pcsrx_config_reg[15:8] <= clockdomainsrenamer1_next_value1;
	end
	k7_1000basex_pcs_lp_abi_starter <= 1'd0;
	if (k7_1000basex_pcs_lp_abi_pong_o) begin
		k7_1000basex_pcs_lp_abi_ibuffer <= k7_1000basex_pcs_lp_abi_i;
	end
	if (k7_1000basex_pcs_lp_abi_ping_i) begin
		k7_1000basex_pcs_lp_abi_ping_toggle_i <= (~k7_1000basex_pcs_lp_abi_ping_toggle_i);
	end
	k7_1000basex_pcs_lp_abi_pong_toggle_o_r <= k7_1000basex_pcs_lp_abi_pong_toggle_o;
	if (k7_1000basex_pcs_lp_abi_wait) begin
		if ((~k7_1000basex_pcs_lp_abi_done)) begin
			k7_1000basex_pcs_lp_abi_count <= (k7_1000basex_pcs_lp_abi_count - 1'd1);
		end
	end else begin
		k7_1000basex_pcs_lp_abi_count <= 8'd128;
	end
	if (k7_1000basex_pcs_seen_valid_ci_i) begin
		k7_1000basex_pcs_seen_valid_ci_toggle_i <= (~k7_1000basex_pcs_seen_valid_ci_toggle_i);
	end
	if (k7_1000basex_pcs_rx_config_reg_abi_i) begin
		k7_1000basex_pcs_rx_config_reg_abi_toggle_i <= (~k7_1000basex_pcs_rx_config_reg_abi_toggle_i);
	end
	if (k7_1000basex_pcs_rx_config_reg_ack_i) begin
		k7_1000basex_pcs_rx_config_reg_ack_toggle_i <= (~k7_1000basex_pcs_rx_config_reg_ack_toggle_i);
	end
	if ((k7_1000basex_phase_half == k7_1000basex_phase_half_rereg)) begin
		k7_1000basex_rx_data1 <= k7_1000basex_rx_data_half[19:10];
	end else begin
		k7_1000basex_rx_data1 <= k7_1000basex_rx_data_half[9:0];
	end
	k7_1000basex_phase_half <= (~k7_1000basex_phase_half);
	if (eth_rx_rst) begin
		k7_1000basex_pcs_pcsrx_config_reg <= 16'd0;
		k7_1000basex_pcs_pcsrx_decoder_k <= 1'd0;
		k7_1000basex_pcs_pcsrx_count0 <= 1'd0;
		k7_1000basex_pcs_pcsrx_count1 <= 7'd0;
		k7_1000basex_pcs_pcsrx_pipe_valid_source_valid <= 1'd0;
		k7_1000basex_pcs_lp_abi_i <= 16'd0;
		k7_1000basex_pcs_lp_abi_starter <= 1'd1;
		k7_1000basex_pcs_lp_abi_count <= 8'd128;
		k7_1000basex_pcs_rx_config_reg_abi_i <= 1'd0;
		k7_1000basex_pcs_rx_config_reg_ack_i <= 1'd0;
		k7_1000basex_pcs_rx_config_reg_count <= 4'd0;
		k7_1000basex_pcs_rx_config_reg_last <= 16'd0;
		k7_1000basex_rx_data1 <= 10'd0;
		k7_1000basex_phase_half <= 1'd0;
		clockdomainsrenamer1_state <= 3'd0;
	end
	xilinxmultiregimpl10 <= k7_1000basex_pcs_lp_abi_pong_toggle_i;
	xilinxmultiregimpl11 <= xilinxmultiregimpl10;
end

always @(posedge eth_rx_half_clk) begin
	k7_1000basex_phase_half_rereg <= k7_1000basex_phase_half;
end

always @(posedge eth_tx_clk) begin
	k7_1000basex_pcs_checker_tick <= 1'd0;
	if ((k7_1000basex_pcs_checker_count == 1'd0)) begin
		k7_1000basex_pcs_checker_tick <= 1'd1;
		k7_1000basex_pcs_checker_count <= 20'd750000;
	end else begin
		k7_1000basex_pcs_checker_count <= (k7_1000basex_pcs_checker_count - 1'd1);
	end
	if (k7_1000basex_pcs_seen_valid_ci_o) begin
		k7_1000basex_pcs_checker_error <= 1'd0;
	end
	if (k7_1000basex_pcs_checker_tick) begin
		k7_1000basex_pcs_checker_error <= 1'd1;
	end
	k7_1000basex_pcs_pcstx_parity <= (~k7_1000basex_pcs_pcstx_parity);
	if (k7_1000basex_pcs_pcstx_encoder_ce0) begin
		k7_1000basex_pcs_pcstx_encoder_disp_in <= k7_1000basex_pcs_pcstx_encoder_disp_out;
	end
	if (k7_1000basex_pcs_pcstx_encoder_ce0) begin
		k7_1000basex_pcs_pcstx_encoder2 <= k7_1000basex_pcs_pcstx_encoder_output;
		k7_1000basex_pcs_pcstx_encoder3 <= k7_1000basex_pcs_pcstx_encoder_disp_out;
	end
	if (k7_1000basex_pcs_pcstx_encoder_ce1) begin
		if ((k7_1000basex_pcs_pcstx_encoder_k & (k7_1000basex_pcs_pcstx_encoder_d[4:0] == 5'd28))) begin
			k7_1000basex_pcs_pcstx_encoder_code6b <= 6'd48;
			k7_1000basex_pcs_pcstx_encoder_code6b_unbalanced <= 1'd1;
			k7_1000basex_pcs_pcstx_encoder_code6b_flip <= 1'd1;
		end else begin
			k7_1000basex_pcs_pcstx_encoder_code6b <= rhs_self0;
			k7_1000basex_pcs_pcstx_encoder_code6b_unbalanced <= rhs_self1;
			k7_1000basex_pcs_pcstx_encoder_code6b_flip <= rhs_self2;
		end
		k7_1000basex_pcs_pcstx_encoder_code4b <= rhs_self3;
		k7_1000basex_pcs_pcstx_encoder_code4b_unbalanced <= rhs_self4;
		if (k7_1000basex_pcs_pcstx_encoder_k) begin
			k7_1000basex_pcs_pcstx_encoder_code4b_flip <= 1'd1;
		end else begin
			k7_1000basex_pcs_pcstx_encoder_code4b_flip <= rhs_self5;
		end
		k7_1000basex_pcs_pcstx_encoder_alt7_rd0 <= 1'd0;
		k7_1000basex_pcs_pcstx_encoder_alt7_rd1 <= 1'd0;
		if ((k7_1000basex_pcs_pcstx_encoder_d[7:5] == 3'd7)) begin
			if ((((k7_1000basex_pcs_pcstx_encoder_d[4:0] == 5'd17) | (k7_1000basex_pcs_pcstx_encoder_d[4:0] == 5'd18)) | (k7_1000basex_pcs_pcstx_encoder_d[4:0] == 5'd20))) begin
				k7_1000basex_pcs_pcstx_encoder_alt7_rd0 <= 1'd1;
			end
			if ((((k7_1000basex_pcs_pcstx_encoder_d[4:0] == 4'd11) | (k7_1000basex_pcs_pcstx_encoder_d[4:0] == 4'd13)) | (k7_1000basex_pcs_pcstx_encoder_d[4:0] == 4'd14))) begin
				k7_1000basex_pcs_pcstx_encoder_alt7_rd1 <= 1'd1;
			end
			if (k7_1000basex_pcs_pcstx_encoder_k) begin
				k7_1000basex_pcs_pcstx_encoder_alt7_rd0 <= 1'd1;
				k7_1000basex_pcs_pcstx_encoder_alt7_rd1 <= 1'd1;
			end
		end
	end
	k7_1000basex_pcs_pcstx_count1 <= (k7_1000basex_pcs_pcstx_count1 - 1'd1);
	if (((~k7_1000basex_pcs_pcstx_enable) | k7_1000basex_pcs_pcstx_done)) begin
		case (k7_1000basex_pcs_pcstx_sgmii_speed)
			1'd0: begin
				k7_1000basex_pcs_pcstx_count1 <= 7'd99;
			end
			1'd1: begin
				k7_1000basex_pcs_pcstx_count1 <= 4'd9;
			end
			2'd2: begin
				k7_1000basex_pcs_pcstx_count1 <= 1'd0;
			end
		endcase
	end
	clockdomainsrenamer0_state <= clockdomainsrenamer0_next_state;
	if (k7_1000basex_pcs_pcstx_count0_clockdomainsrenamer0_next_value_ce0) begin
		k7_1000basex_pcs_pcstx_count0 <= k7_1000basex_pcs_pcstx_count0_clockdomainsrenamer0_next_value0;
	end
	if (k7_1000basex_pcs_pcstx_ctype_clockdomainsrenamer0_next_value_ce1) begin
		k7_1000basex_pcs_pcstx_ctype <= k7_1000basex_pcs_pcstx_ctype_clockdomainsrenamer0_next_value1;
	end
	k7_1000basex_pcs_lp_abi_ping_o1 <= k7_1000basex_pcs_lp_abi_ping_o0;
	if (k7_1000basex_pcs_lp_abi_ping_o1) begin
		k7_1000basex_pcs_lp_abi_o <= k7_1000basex_pcs_lp_abi_obuffer;
	end
	k7_1000basex_pcs_lp_abi_ping_toggle_o_r <= k7_1000basex_pcs_lp_abi_ping_toggle_o;
	if (k7_1000basex_pcs_lp_abi_pong_i) begin
		k7_1000basex_pcs_lp_abi_pong_toggle_i <= (~k7_1000basex_pcs_lp_abi_pong_toggle_i);
	end
	k7_1000basex_pcs_seen_valid_ci_toggle_o_r <= k7_1000basex_pcs_seen_valid_ci_toggle_o;
	k7_1000basex_pcs_rx_config_reg_abi_toggle_o_r <= k7_1000basex_pcs_rx_config_reg_abi_toggle_o;
	k7_1000basex_pcs_rx_config_reg_ack_toggle_o_r <= k7_1000basex_pcs_rx_config_reg_ack_toggle_o;
	if (k7_1000basex_pcs_waittimer0_wait) begin
		if ((~k7_1000basex_pcs_waittimer0_done)) begin
			k7_1000basex_pcs_waittimer0_count <= (k7_1000basex_pcs_waittimer0_count - 1'd1);
		end
	end else begin
		k7_1000basex_pcs_waittimer0_count <= 21'd1250000;
	end
	if (k7_1000basex_pcs_waittimer1_wait) begin
		if ((~k7_1000basex_pcs_waittimer1_done)) begin
			k7_1000basex_pcs_waittimer1_count <= (k7_1000basex_pcs_waittimer1_count - 1'd1);
		end
	end else begin
		k7_1000basex_pcs_waittimer1_count <= 21'd1250000;
	end
	if (k7_1000basex_pcs_waittimer2_wait) begin
		if ((~k7_1000basex_pcs_waittimer2_done)) begin
			k7_1000basex_pcs_waittimer2_count <= (k7_1000basex_pcs_waittimer2_count - 1'd1);
		end
	end else begin
		k7_1000basex_pcs_waittimer2_count <= 18'd200000;
	end
	clockdomainsrenamer2_state <= clockdomainsrenamer2_next_state;
	if (k7_1000basex_i) begin
		k7_1000basex_toggle_i <= (~k7_1000basex_toggle_i);
	end
	k7_1000basex_buf <= {k7_1000basex_tx_data1, k7_1000basex_buf[19:10]};
	if (eth_tx_rst) begin
		k7_1000basex_pcs_pcstx_encoder3 <= 1'd0;
		k7_1000basex_pcs_pcstx_encoder_disp_in <= 1'd0;
		k7_1000basex_pcs_pcstx_encoder_code6b_flip <= 1'd0;
		k7_1000basex_pcs_pcstx_encoder_code4b_flip <= 1'd0;
		k7_1000basex_pcs_pcstx_count0 <= 1'd0;
		k7_1000basex_pcs_pcstx_parity <= 1'd0;
		k7_1000basex_pcs_pcstx_ctype <= 1'd0;
		k7_1000basex_pcs_pcstx_count1 <= 7'd0;
		k7_1000basex_pcs_lp_abi_ping_o1 <= 1'd0;
		k7_1000basex_pcs_waittimer0_count <= 21'd1250000;
		k7_1000basex_pcs_waittimer1_count <= 21'd1250000;
		k7_1000basex_pcs_waittimer2_count <= 18'd200000;
		k7_1000basex_pcs_checker_count <= 20'd0;
		k7_1000basex_pcs_checker_tick <= 1'd0;
		k7_1000basex_pcs_checker_error <= 1'd0;
		k7_1000basex_buf <= 20'd0;
		clockdomainsrenamer0_state <= 3'd0;
		clockdomainsrenamer2_state <= 3'd0;
	end
	xilinxmultiregimpl00 <= k7_1000basex_pcs_lp_abi_ping_toggle_i;
	xilinxmultiregimpl01 <= xilinxmultiregimpl00;
	xilinxmultiregimpl20 <= k7_1000basex_pcs_lp_abi_ibuffer;
	xilinxmultiregimpl21 <= xilinxmultiregimpl20;
	xilinxmultiregimpl30 <= k7_1000basex_pcs_seen_valid_ci_toggle_i;
	xilinxmultiregimpl31 <= xilinxmultiregimpl30;
	xilinxmultiregimpl40 <= k7_1000basex_pcs_rx_config_reg_abi_toggle_i;
	xilinxmultiregimpl41 <= xilinxmultiregimpl40;
	xilinxmultiregimpl50 <= k7_1000basex_pcs_rx_config_reg_ack_toggle_i;
	xilinxmultiregimpl51 <= xilinxmultiregimpl50;
end

always @(posedge eth_tx_half_clk) begin
	k7_1000basex_tx_data_half <= k7_1000basex_buf;
end

always @(posedge sys_clk) begin
	k7_1000basex_tx_mmcm_reset0 <= (~k7_1000basex_pll_lock);
	if (k7_1000basex_rx_reset) begin
		k7_1000basex_cdr_locked <= 1'd0;
		k7_1000basex_cdr_lock_counter <= 1'd0;
	end else begin
		if ((k7_1000basex_cdr_lock_counter != 10'd1000)) begin
			k7_1000basex_cdr_lock_counter <= (k7_1000basex_cdr_lock_counter + 1'd1);
		end else begin
			k7_1000basex_cdr_locked <= 1'd1;
		end
	end
	k7_1000basex_rx_mmcm_reset0 <= (~k7_1000basex_cdr_locked);
	k7_1000basex_gtxtxinit_Xxphaligndone_r <= k7_1000basex_gtxtxinit_Xxphaligndone1;
	k7_1000basex_gtxtxinit_pllreset0 <= k7_1000basex_gtxtxinit_pllreset1;
	k7_1000basex_gtxtxinit_gtXxreset0 <= k7_1000basex_gtxtxinit_gtXxreset1;
	k7_1000basex_gtxtxinit_gtXxpd0 <= k7_1000basex_gtxtxinit_gtXxpd1;
	k7_1000basex_gtxtxinit_Xxdlysreset0 <= k7_1000basex_gtxtxinit_Xxdlysreset1;
	k7_1000basex_gtxtxinit_Xxuserrdy0 <= k7_1000basex_gtxtxinit_Xxuserrdy1;
	gtxtxinit_state <= gtxtxinit_next_state;
	if (k7_1000basex_gtxtxinit_reset) begin
		gtxtxinit_state <= 4'd0;
	end
	if (k7_1000basex_gtxtxinit_init_delay_wait) begin
		if ((~k7_1000basex_gtxtxinit_init_delay_done)) begin
			k7_1000basex_gtxtxinit_init_delay_count <= (k7_1000basex_gtxtxinit_init_delay_count - 1'd1);
		end
	end else begin
		k7_1000basex_gtxtxinit_init_delay_count <= 4'd12;
	end
	if (k7_1000basex_gtxtxinit_cdr_lock_timer_wait) begin
		if ((~k7_1000basex_gtxtxinit_cdr_lock_timer_done)) begin
			k7_1000basex_gtxtxinit_cdr_lock_timer_count <= (k7_1000basex_gtxtxinit_cdr_lock_timer_count - 1'd1);
		end
	end else begin
		k7_1000basex_gtxtxinit_cdr_lock_timer_count <= 11'd1024;
	end
	if (k7_1000basex_gtxtxinit_watchdog_wait) begin
		if ((~k7_1000basex_gtxtxinit_watchdog_done)) begin
			k7_1000basex_gtxtxinit_watchdog_count <= (k7_1000basex_gtxtxinit_watchdog_count - 1'd1);
		end
	end else begin
		k7_1000basex_gtxtxinit_watchdog_count <= 15'd25000;
	end
	if (k7_1000basex_tx_init_reset) begin
		k7_1000basex_gtxtxinit_pllreset0 <= 1'd0;
		k7_1000basex_gtxtxinit_gtXxreset0 <= 1'd0;
		k7_1000basex_gtxtxinit_gtXxpd0 <= 1'd0;
		k7_1000basex_gtxtxinit_Xxdlysreset0 <= 1'd0;
		k7_1000basex_gtxtxinit_Xxuserrdy0 <= 1'd0;
		k7_1000basex_gtxtxinit_Xxphaligndone_r <= 1'd1;
		k7_1000basex_gtxtxinit_init_delay_count <= 4'd12;
		k7_1000basex_gtxtxinit_cdr_lock_timer_count <= 11'd1024;
		k7_1000basex_gtxtxinit_watchdog_count <= 15'd25000;
		gtxtxinit_state <= 4'd0;
	end
	k7_1000basex_gtxrxinit_Xxphaligndone_r <= k7_1000basex_gtxrxinit_Xxphaligndone1;
	k7_1000basex_gtxrxinit_pllreset0 <= k7_1000basex_gtxrxinit_pllreset1;
	k7_1000basex_gtxrxinit_gtXxreset0 <= k7_1000basex_gtxrxinit_gtXxreset1;
	k7_1000basex_gtxrxinit_gtXxpd0 <= k7_1000basex_gtxrxinit_gtXxpd1;
	k7_1000basex_gtxrxinit_Xxdlysreset0 <= k7_1000basex_gtxrxinit_Xxdlysreset1;
	k7_1000basex_gtxrxinit_Xxuserrdy0 <= k7_1000basex_gtxrxinit_Xxuserrdy1;
	gtxrxinit_state <= gtxrxinit_next_state;
	if (k7_1000basex_gtxrxinit_reset) begin
		gtxrxinit_state <= 4'd0;
	end
	if (k7_1000basex_gtxrxinit_init_delay_wait) begin
		if ((~k7_1000basex_gtxrxinit_init_delay_done)) begin
			k7_1000basex_gtxrxinit_init_delay_count <= (k7_1000basex_gtxrxinit_init_delay_count - 1'd1);
		end
	end else begin
		k7_1000basex_gtxrxinit_init_delay_count <= 4'd12;
	end
	if (k7_1000basex_gtxrxinit_cdr_lock_timer_wait) begin
		if ((~k7_1000basex_gtxrxinit_cdr_lock_timer_done)) begin
			k7_1000basex_gtxrxinit_cdr_lock_timer_count <= (k7_1000basex_gtxrxinit_cdr_lock_timer_count - 1'd1);
		end
	end else begin
		k7_1000basex_gtxrxinit_cdr_lock_timer_count <= 11'd1024;
	end
	if (k7_1000basex_gtxrxinit_watchdog_wait) begin
		if ((~k7_1000basex_gtxrxinit_watchdog_done)) begin
			k7_1000basex_gtxrxinit_watchdog_count <= (k7_1000basex_gtxrxinit_watchdog_count - 1'd1);
		end
	end else begin
		k7_1000basex_gtxrxinit_watchdog_count <= 15'd25000;
	end
	if (k7_1000basex_rx_init_reset) begin
		k7_1000basex_gtxrxinit_pllreset0 <= 1'd0;
		k7_1000basex_gtxrxinit_gtXxreset0 <= 1'd0;
		k7_1000basex_gtxrxinit_gtXxpd0 <= 1'd0;
		k7_1000basex_gtxrxinit_Xxdlysreset0 <= 1'd0;
		k7_1000basex_gtxrxinit_Xxuserrdy0 <= 1'd0;
		k7_1000basex_gtxrxinit_Xxphaligndone_r <= 1'd1;
		k7_1000basex_gtxrxinit_init_delay_count <= 4'd12;
		k7_1000basex_gtxrxinit_cdr_lock_timer_count <= 11'd1024;
		k7_1000basex_gtxrxinit_watchdog_count <= 15'd25000;
		gtxrxinit_state <= 4'd0;
	end
	k7_1000basex_toggle_o_r <= k7_1000basex_toggle_o;
	if (sys_rst) begin
		k7_1000basex_tx_mmcm_reset0 <= 1'd1;
		k7_1000basex_rx_mmcm_reset0 <= 1'd1;
		k7_1000basex_gtxtxinit_pllreset0 <= 1'd0;
		k7_1000basex_gtxtxinit_gtXxreset0 <= 1'd0;
		k7_1000basex_gtxtxinit_gtXxpd0 <= 1'd0;
		k7_1000basex_gtxtxinit_Xxdlysreset0 <= 1'd0;
		k7_1000basex_gtxtxinit_Xxuserrdy0 <= 1'd0;
		k7_1000basex_gtxtxinit_Xxphaligndone_r <= 1'd1;
		k7_1000basex_gtxtxinit_init_delay_count <= 4'd12;
		k7_1000basex_gtxtxinit_cdr_lock_timer_count <= 11'd1024;
		k7_1000basex_gtxtxinit_watchdog_count <= 15'd25000;
		k7_1000basex_gtxrxinit_pllreset0 <= 1'd0;
		k7_1000basex_gtxrxinit_gtXxreset0 <= 1'd0;
		k7_1000basex_gtxrxinit_gtXxpd0 <= 1'd0;
		k7_1000basex_gtxrxinit_Xxdlysreset0 <= 1'd0;
		k7_1000basex_gtxrxinit_Xxuserrdy0 <= 1'd0;
		k7_1000basex_gtxrxinit_Xxphaligndone_r <= 1'd1;
		k7_1000basex_gtxrxinit_init_delay_count <= 4'd12;
		k7_1000basex_gtxrxinit_cdr_lock_timer_count <= 11'd1024;
		k7_1000basex_gtxrxinit_watchdog_count <= 15'd25000;
		k7_1000basex_cdr_lock_counter <= 10'd0;
		k7_1000basex_cdr_locked <= 1'd0;
		gtxtxinit_state <= 4'd0;
		gtxrxinit_state <= 4'd0;
	end
	xilinxmultiregimpl60 <= k7_1000basex_gtxtxinit_plllock0;
	xilinxmultiregimpl61 <= xilinxmultiregimpl60;
	xilinxmultiregimpl70 <= k7_1000basex_gtxtxinit_Xxresetdone0;
	xilinxmultiregimpl71 <= xilinxmultiregimpl70;
	xilinxmultiregimpl80 <= k7_1000basex_gtxtxinit_Xxdlysresetdone0;
	xilinxmultiregimpl81 <= xilinxmultiregimpl80;
	xilinxmultiregimpl90 <= k7_1000basex_gtxtxinit_Xxphaligndone0;
	xilinxmultiregimpl91 <= xilinxmultiregimpl90;
	xilinxmultiregimpl100 <= k7_1000basex_gtxrxinit_plllock0;
	xilinxmultiregimpl101 <= xilinxmultiregimpl100;
	xilinxmultiregimpl110 <= k7_1000basex_gtxrxinit_Xxresetdone0;
	xilinxmultiregimpl111 <= xilinxmultiregimpl110;
	xilinxmultiregimpl120 <= k7_1000basex_gtxrxinit_Xxdlysresetdone0;
	xilinxmultiregimpl121 <= xilinxmultiregimpl120;
	xilinxmultiregimpl130 <= k7_1000basex_gtxrxinit_Xxphaligndone0;
	xilinxmultiregimpl131 <= xilinxmultiregimpl130;
	xilinxmultiregimpl140 <= k7_1000basex_toggle_i;
	xilinxmultiregimpl141 <= xilinxmultiregimpl140;
end

reg [4:0] mem_6b5b[0:63];
reg [5:0] memadr;
always @(posedge eth_rx_clk) begin : mem_write_block
	if (k7_1000basex_pcs_pcsrx_decoder_re)
		memadr <= k7_1000basex_pcs_pcsrx_decoder_adr;
end

assign k7_1000basex_pcs_pcsrx_decoder_dat_r = mem_6b5b[memadr];

initial begin
	// mem_6b5b.init, inlined -- see gen_liteeth_phy.py
	mem_6b5b[0] = 'h0;
	mem_6b5b[1] = 'h0;
	mem_6b5b[2] = 'h0;
	mem_6b5b[3] = 'h0;
	mem_6b5b[4] = 'h0;
	mem_6b5b[5] = 'h17;
	mem_6b5b[6] = 'h8;
	mem_6b5b[7] = 'h7;
	mem_6b5b[8] = 'h0;
	mem_6b5b[9] = 'h1B;
	mem_6b5b[10] = 'h4;
	mem_6b5b[11] = 'h14;
	mem_6b5b[12] = 'h18;
	mem_6b5b[13] = 'hC;
	mem_6b5b[14] = 'h1C;
	mem_6b5b[15] = 'h1C;
	mem_6b5b[16] = 'h0;
	mem_6b5b[17] = 'h1D;
	mem_6b5b[18] = 'h2;
	mem_6b5b[19] = 'h12;
	mem_6b5b[20] = 'h1F;
	mem_6b5b[21] = 'hA;
	mem_6b5b[22] = 'h1A;
	mem_6b5b[23] = 'hF;
	mem_6b5b[24] = 'h0;
	mem_6b5b[25] = 'h6;
	mem_6b5b[26] = 'h16;
	mem_6b5b[27] = 'h10;
	mem_6b5b[28] = 'hE;
	mem_6b5b[29] = 'h1;
	mem_6b5b[30] = 'h1E;
	mem_6b5b[31] = 'h0;
	mem_6b5b[32] = 'h0;
	mem_6b5b[33] = 'h1E;
	mem_6b5b[34] = 'h1;
	mem_6b5b[35] = 'h11;
	mem_6b5b[36] = 'h10;
	mem_6b5b[37] = 'h9;
	mem_6b5b[38] = 'h19;
	mem_6b5b[39] = 'h0;
	mem_6b5b[40] = 'hF;
	mem_6b5b[41] = 'h5;
	mem_6b5b[42] = 'h15;
	mem_6b5b[43] = 'h1F;
	mem_6b5b[44] = 'hD;
	mem_6b5b[45] = 'h2;
	mem_6b5b[46] = 'h1D;
	mem_6b5b[47] = 'h0;
	mem_6b5b[48] = 'h1C;
	mem_6b5b[49] = 'h3;
	mem_6b5b[50] = 'h13;
	mem_6b5b[51] = 'h18;
	mem_6b5b[52] = 'hB;
	mem_6b5b[53] = 'h4;
	mem_6b5b[54] = 'h1B;
	mem_6b5b[55] = 'h0;
	mem_6b5b[56] = 'h7;
	mem_6b5b[57] = 'h8;
	mem_6b5b[58] = 'h17;
	mem_6b5b[59] = 'h0;
	mem_6b5b[60] = 'h0;
	mem_6b5b[61] = 'h0;
	mem_6b5b[62] = 'h0;
	mem_6b5b[63] = 'h0;
end

IBUFDS_GTE2 #(
	.CLKCM_CFG("TRUE"),
	.CLKRCV_TRST("TRUE"),
	.CLKSWING_CFG(2'b11)
) IBUFDS_GTE2(
	.CEB(1'd0),
	.I(sgmii_refclk_p),
	.IB(sgmii_refclk_n),
	.O(k7_1000basex_refclk)
);

GTXE2_CHANNEL #(
	.ALIGN_COMMA_DOUBLE("FALSE"),
	.ALIGN_COMMA_ENABLE(10'd1023),
	.ALIGN_COMMA_WORD(2'd2),
	.ALIGN_MCOMMA_DET("TRUE"),
	.ALIGN_MCOMMA_VALUE(10'd643),
	.ALIGN_PCOMMA_DET("TRUE"),
	.ALIGN_PCOMMA_VALUE(9'd380),
	.CBCC_DATA_SOURCE_SEL("DECODED"),
	.CHAN_BOND_KEEP_ALIGN("FALSE"),
	.CHAN_BOND_MAX_SKEW(1'd1),
	.CHAN_BOND_SEQ_1_1(1'd0),
	.CHAN_BOND_SEQ_1_2(1'd0),
	.CHAN_BOND_SEQ_1_3(1'd0),
	.CHAN_BOND_SEQ_1_4(1'd0),
	.CHAN_BOND_SEQ_1_ENABLE(4'd15),
	.CHAN_BOND_SEQ_2_1(1'd0),
	.CHAN_BOND_SEQ_2_2(1'd0),
	.CHAN_BOND_SEQ_2_3(1'd0),
	.CHAN_BOND_SEQ_2_4(1'd0),
	.CHAN_BOND_SEQ_2_ENABLE(4'd15),
	.CHAN_BOND_SEQ_2_USE("FALSE"),
	.CHAN_BOND_SEQ_LEN(1'd1),
	.CLK_CORRECT_USE("FALSE"),
	.CLK_COR_KEEP_IDLE("FALSE"),
	.CLK_COR_MAX_LAT(4'd9),
	.CLK_COR_MIN_LAT(3'd7),
	.CLK_COR_PRECEDENCE("TRUE"),
	.CLK_COR_REPEAT_WAIT(1'd0),
	.CLK_COR_SEQ_1_1(9'd256),
	.CLK_COR_SEQ_1_2(1'd0),
	.CLK_COR_SEQ_1_3(1'd0),
	.CLK_COR_SEQ_1_4(1'd0),
	.CLK_COR_SEQ_1_ENABLE(4'd15),
	.CLK_COR_SEQ_2_1(9'd256),
	.CLK_COR_SEQ_2_2(1'd0),
	.CLK_COR_SEQ_2_3(1'd0),
	.CLK_COR_SEQ_2_4(1'd0),
	.CLK_COR_SEQ_2_ENABLE(4'd15),
	.CLK_COR_SEQ_2_USE("FALSE"),
	.CLK_COR_SEQ_LEN(1'd1),
	.CPLL_CFG(24'd12322780),
	.CPLL_FBDIV(3'd5),
	.CPLL_FBDIV_45(3'd4),
	.CPLL_INIT_CFG(5'd30),
	.CPLL_LOCK_CFG(9'd488),
	.CPLL_REFCLK_DIV(1'd1),
	.DEC_MCOMMA_DETECT("TRUE"),
	.DEC_PCOMMA_DETECT("TRUE"),
	.DEC_VALID_COMMA_ONLY("TRUE"),
	.DMONITOR_CFG(12'd2560),
	.ES_CONTROL(1'd0),
	.ES_ERRDET_EN("FALSE"),
	.ES_EYE_SCAN_EN("TRUE"),
	.ES_HORZ_OFFSET(1'd0),
	.ES_PMA_CFG(1'd0),
	.ES_PRESCALE(1'd0),
	.ES_QUALIFIER(1'd0),
	.ES_QUAL_MASK(1'd0),
	.ES_SDATA_MASK(1'd0),
	.ES_VERT_OFFSET(1'd0),
	.FTS_DESKEW_SEQ_ENABLE(4'd15),
	.FTS_LANE_DESKEW_CFG(4'd15),
	.FTS_LANE_DESKEW_EN("FALSE"),
	.GEARBOX_MODE(1'd0),
	.OUTREFCLK_SEL_INV(2'd3),
	.PCS_PCIE_EN("FALSE"),
	.PCS_RSVD_ATTR(1'd0),
	.PD_TRANS_TIME_FROM_P2(6'd60),
	.PD_TRANS_TIME_NONE_P2(6'd60),
	.PD_TRANS_TIME_TO_P2(7'd100),
	.PMA_RSV(21'd1994880),
	.PMA_RSV2(14'd8272),
	.PMA_RSV3(1'd0),
	.PMA_RSV4(1'd0),
	.RXBUFRESET_TIME(1'd1),
	.RXBUF_ADDR_MODE("FAST"),
	.RXBUF_EIDLE_HI_CNT(4'd8),
	.RXBUF_EIDLE_LO_CNT(1'd0),
	.RXBUF_EN("TRUE"),
	.RXBUF_RESET_ON_CB_CHANGE("TRUE"),
	.RXBUF_RESET_ON_COMMAALIGN("FALSE"),
	.RXBUF_RESET_ON_EIDLE("FALSE"),
	.RXBUF_RESET_ON_RATE_CHANGE("TRUE"),
	.RXBUF_THRESH_OVFLW(6'd61),
	.RXBUF_THRESH_OVRD("FALSE"),
	.RXBUF_THRESH_UNDFLW(3'd4),
	.RXCDRFREQRESET_TIME(1'd1),
	.RXCDRPHRESET_TIME(1'd1),
	.RXCDR_CFG(66'd55340271799521771552),
	.RXCDR_FR_RESET_ON_EIDLE(1'd0),
	.RXCDR_HOLD_DURING_EIDLE(1'd0),
	.RXCDR_LOCK_CFG(5'd21),
	.RXCDR_PH_RESET_ON_EIDLE(1'd0),
	.RXDFELPMRESET_TIME(4'd15),
	.RXDLY_CFG(5'd31),
	.RXDLY_LCFG(6'd48),
	.RXDLY_TAP_CFG(1'd0),
	.RXGEARBOX_EN("FALSE"),
	.RXISCANRESET_TIME(1'd1),
	.RXLPM_HF_CFG(8'd240),
	.RXLPM_LF_CFG(8'd240),
	.RXOOB_CFG(3'd6),
	.RXOUT_DIV(3'd4),
	.RXPCSRESET_TIME(1'd1),
	.RXPHDLY_CFG(20'd540704),
	.RXPH_CFG(1'd0),
	.RXPH_MONITOR_SEL(1'd0),
	.RXPMARESET_TIME(2'd3),
	.RXPRBS_ERR_LOOPBACK(1'd0),
	.RXSLIDE_AUTO_WAIT(3'd7),
	.RXSLIDE_MODE("OFF"),
	.RX_BIAS_CFG(3'd4),
	.RX_BUFFER_CFG(1'd0),
	.RX_CLK25_DIV(3'd5),
	.RX_CLKMUX_PD(1'd1),
	.RX_CM_SEL(2'd3),
	.RX_CM_TRIM(2'd2),
	.RX_DATA_WIDTH(5'd20),
	.RX_DDI_SEL(1'd0),
	.RX_DEBUG_CFG(1'd0),
	.RX_DEFER_RESET_BUF_EN("TRUE"),
	.RX_DFE_GAIN_CFG(18'd135146),
	.RX_DFE_H2_CFG(1'd0),
	.RX_DFE_H3_CFG(7'd64),
	.RX_DFE_H4_CFG(8'd240),
	.RX_DFE_H5_CFG(8'd224),
	.RX_DFE_KL_CFG(8'd254),
	.RX_DFE_KL_CFG2(30'd806439084),
	.RX_DFE_LPM_CFG(12'd2388),
	.RX_DFE_LPM_HOLD_DURING_EIDLE(1'd0),
	.RX_DFE_UT_CFG(17'd73216),
	.RX_DFE_VP_CFG(14'd16131),
	.RX_DFE_XYD_CFG(1'd0),
	.RX_DISPERR_SEQ_MATCH("TRUE"),
	.RX_INT_DATAWIDTH(1'd0),
	.RX_OS_CFG(8'd128),
	.RX_SIG_VALID_DLY(4'd10),
	.RX_XCLK_SEL("RXREC"),
	.SAS_MAX_COM(7'd64),
	.SAS_MIN_COM(6'd36),
	.SATA_BURST_SEQ_LEN(3'd5),
	.SATA_BURST_VAL(3'd4),
	.SATA_CPLL_CFG("VCO_3000MHZ"),
	.SATA_EIDLE_VAL(3'd4),
	.SATA_MAX_BURST(4'd8),
	.SATA_MAX_INIT(5'd21),
	.SATA_MAX_WAKE(3'd7),
	.SATA_MIN_BURST(3'd4),
	.SATA_MIN_INIT(4'd12),
	.SATA_MIN_WAKE(3'd4),
	.SHOW_REALIGN_COMMA("TRUE"),
	.SIM_CPLLREFCLK_SEL("FALSE"),
	.SIM_RECEIVER_DETECT_PASS("TRUE"),
	.SIM_RESET_SPEEDUP("FALSE"),
	.SIM_TX_EIDLE_DRIVE_LEVEL("X"),
	.SIM_VERSION("4.0"),
	.TERM_RCAL_CFG(5'd16),
	.TERM_RCAL_OVRD(1'd0),
	.TRANS_TIME_RATE(4'd14),
	.TST_RSV(1'd0),
	.TXBUF_EN("TRUE"),
	.TXBUF_RESET_ON_RATE_CHANGE("TRUE"),
	.TXDLY_CFG(5'd31),
	.TXDLY_LCFG(6'd48),
	.TXDLY_TAP_CFG(1'd0),
	.TXGEARBOX_EN("FALSE"),
	.TXOUT_DIV(3'd4),
	.TXPCSRESET_TIME(1'd1),
	.TXPHDLY_CFG(20'd540704),
	.TXPH_CFG(11'd1920),
	.TXPH_MONITOR_SEL(1'd0),
	.TXPMARESET_TIME(1'd1),
	.TX_CLK25_DIV(3'd5),
	.TX_CLKMUX_PD(1'd1),
	.TX_DATA_WIDTH(5'd20),
	.TX_DEEMPH0(1'd0),
	.TX_DEEMPH1(1'd0),
	.TX_DRIVE_MODE("DIRECT"),
	.TX_EIDLE_ASSERT_DELAY(3'd6),
	.TX_EIDLE_DEASSERT_DELAY(3'd4),
	.TX_INT_DATAWIDTH(1'd0),
	.TX_LOOPBACK_DRIVE_HIZ("FALSE"),
	.TX_MAINCURSOR_SEL(1'd0),
	.TX_MARGIN_FULL_0(7'd78),
	.TX_MARGIN_FULL_1(7'd73),
	.TX_MARGIN_FULL_2(7'd69),
	.TX_MARGIN_FULL_3(7'd66),
	.TX_MARGIN_FULL_4(7'd64),
	.TX_MARGIN_LOW_0(7'd70),
	.TX_MARGIN_LOW_1(7'd68),
	.TX_MARGIN_LOW_2(7'd66),
	.TX_MARGIN_LOW_3(7'd64),
	.TX_MARGIN_LOW_4(7'd64),
	.TX_PREDRIVER_MODE(1'd0),
	.TX_QPI_STATUS_EN(1'd0),
	.TX_RXDETECT_CFG(13'd6194),
	.TX_RXDETECT_REF(3'd4),
	.TX_XCLK_SEL("TXOUT"),
	.UCODEER_CLR(1'd0)
) GTXE2_CHANNEL (
	.CFGRESET(1'd0),
	.CLKRSVD(1'd0),
	.CPLLLOCKDETCLK(sys_clk),
	.CPLLLOCKEN(1'd1),
	.CPLLPD(1'd0),
	.CPLLREFCLKSEL(1'd1),
	.CPLLRESET(k7_1000basex_pll_reset),
	.DRPADDR(1'd0),
	.DRPCLK(1'd0),
	.DRPDI(1'd0),
	.DRPEN(1'd0),
	.DRPWE(1'd0),
	.EYESCANMODE(1'd0),
	.EYESCANRESET(1'd0),
	.EYESCANTRIGGER(1'd0),
	.GTGREFCLK(1'd0),
	.GTNORTHREFCLK0(1'd0),
	.GTNORTHREFCLK1(1'd0),
	.GTREFCLK0(k7_1000basex_refclk),
	.GTREFCLK1(1'd0),
	.GTRESETSEL(1'd0),
	.GTRSVD(1'd0),
	.GTRXRESET(k7_1000basex_rx_reset),
	.GTSOUTHREFCLK0(1'd0),
	.GTSOUTHREFCLK1(1'd0),
	.GTTXRESET(k7_1000basex_tx_reset),
	.GTXRXN(sgmii_rxn),
	.GTXRXP(sgmii_rxp),
	.LOOPBACK(1'd0),
	.PCSRSVDIN(1'd0),
	.PCSRSVDIN2(1'd0),
	.PMARSVDIN(1'd0),
	.PMARSVDIN2(1'd0),
	.QPLLCLK(1'd0),
	.QPLLREFCLK(1'd0),
	.RESETOVRD(1'd0),
	.RX8B10BEN(1'd0),
	.RXBUFRESET(1'd0),
	.RXCDRFREQRESET(1'd0),
	.RXCDRHOLD(1'd0),
	.RXCDROVRDEN(1'd0),
	.RXCDRRESET(1'd0),
	.RXCDRRESETRSV(1'd0),
	.RXCHBONDEN(1'd0),
	.RXCHBONDI(1'd0),
	.RXCHBONDLEVEL(1'd0),
	.RXCHBONDMASTER(1'd0),
	.RXCHBONDSLAVE(1'd0),
	.RXCOMMADETEN(1'd1),
	.RXDDIEN(1'd0),
	.RXDFEAGCHOLD(1'd0),
	.RXDFEAGCOVRDEN(1'd0),
	.RXDFECM1EN(1'd0),
	.RXDFELFHOLD(1'd0),
	.RXDFELFOVRDEN(1'd1),
	.RXDFELPMRESET(1'd0),
	.RXDFETAP2HOLD(1'd0),
	.RXDFETAP2OVRDEN(1'd0),
	.RXDFETAP3HOLD(1'd0),
	.RXDFETAP3OVRDEN(1'd0),
	.RXDFETAP4HOLD(1'd0),
	.RXDFETAP4OVRDEN(1'd0),
	.RXDFETAP5HOLD(1'd0),
	.RXDFETAP5OVRDEN(1'd0),
	.RXDFEUTHOLD(1'd0),
	.RXDFEUTOVRDEN(1'd0),
	.RXDFEVPHOLD(1'd0),
	.RXDFEVPOVRDEN(1'd0),
	.RXDFEVSEN(1'd0),
	.RXDFEXYDEN(1'd1),
	.RXDFEXYDHOLD(1'd0),
	.RXDFEXYDOVRDEN(1'd0),
	.RXDISPERR({k7_1000basex_rx_data0[19], k7_1000basex_rx_data0[9]}),
	.RXDLYBYPASS(1'd1),
	.RXDLYEN(1'd0),
	.RXDLYOVRDEN(1'd0),
	.RXDLYSRESET(1'd0),
	.RXELECIDLEMODE(2'd3),
	.RXGEARBOXSLIP(1'd0),
	.RXLPMEN(1'd0),
	.RXLPMHFHOLD(1'd0),
	.RXLPMHFOVRDEN(1'd0),
	.RXLPMLFHOLD(1'd0),
	.RXLPMLFKLOVRDEN(1'd0),
	.RXMCOMMAALIGNEN(k7_1000basex_pcs_align),
	.RXMONITORSEL(1'd0),
	.RXOOBRESET(1'd0),
	.RXOSHOLD(1'd0),
	.RXOSOVRDEN(1'd0),
	.RXOUTCLKSEL(2'd2),
	.RXPCOMMAALIGNEN(k7_1000basex_pcs_align),
	.RXPCSRESET(1'd0),
	.RXPD(1'd0),
	.RXPHALIGN(1'd0),
	.RXPHALIGNEN(1'd0),
	.RXPHDLYPD(1'd0),
	.RXPHDLYRESET(1'd0),
	.RXPHOVRDEN(1'd0),
	.RXPMARESET(1'd0),
	.RXPOLARITY(1'd0),
	.RXPRBSCNTRESET(1'd0),
	.RXPRBSSEL(1'd0),
	.RXQPIEN(1'd0),
	.RXRATE(1'd0),
	.RXSLIDE(1'd0),
	.RXSYSCLKSEL(1'd0),
	.RXUSERRDY(k7_1000basex_rx_mmcm_locked0),
	.RXUSRCLK(eth_rx_half_clk),
	.RXUSRCLK2(eth_rx_half_clk),
	.SETERRSTATUS(1'd0),
	.TSTIN(20'd1048575),
	.TX8B10BBYPASS(1'd0),
	.TX8B10BEN(1'd0),
	.TXBUFDIFFCTRL(3'd4),
	.TXCHARDISPMODE({k7_1000basex_tx_data0[19], k7_1000basex_tx_data0[9]}),
	.TXCHARDISPVAL({k7_1000basex_tx_data0[18], k7_1000basex_tx_data0[8]}),
	.TXCHARISK(1'd0),
	.TXCOMINIT(1'd0),
	.TXCOMSAS(1'd0),
	.TXCOMWAKE(1'd0),
	.TXDATA({k7_1000basex_tx_data0[17:10], k7_1000basex_tx_data0[7:0]}),
	.TXDEEMPH(1'd0),
	.TXDETECTRX(1'd0),
	.TXDIFFCTRL(4'd8),
	.TXDIFFPD(1'd0),
	.TXDLYBYPASS(1'd1),
	.TXDLYEN(1'd0),
	.TXDLYHOLD(1'd0),
	.TXDLYOVRDEN(1'd0),
	.TXDLYSRESET(1'd0),
	.TXDLYUPDOWN(1'd0),
	.TXELECIDLE(1'd0),
	.TXHEADER(1'd0),
	.TXINHIBIT(1'd0),
	.TXMAINCURSOR(1'd0),
	.TXMARGIN(1'd0),
	.TXOUTCLKSEL(2'd2),
	.TXPCSRESET(1'd0),
	.TXPD(1'd0),
	.TXPDELECIDLEMODE(1'd0),
	.TXPHALIGN(1'd0),
	.TXPHALIGNEN(1'd0),
	.TXPHDLYPD(1'd0),
	.TXPHDLYRESET(1'd0),
	.TXPHDLYTSTCLK(1'd0),
	.TXPHINIT(1'd0),
	.TXPHOVRDEN(1'd0),
	.TXPISOPD(1'd0),
	.TXPMARESET(1'd0),
	.TXPOLARITY(1'd0),
	.TXPOSTCURSOR(1'd0),
	.TXPOSTCURSORINV(1'd0),
	.TXPRBSFORCEERR(1'd0),
	.TXPRBSSEL(1'd0),
	.TXPRECURSOR(1'd0),
	.TXPRECURSORINV(1'd0),
	.TXQPIBIASEN(1'd0),
	.TXQPISTRONGPDOWN(1'd0),
	.TXQPIWEAKPUP(1'd0),
	.TXRATE(1'd0),
	.TXSEQUENCE(1'd0),
	.TXSTARTSEQ(1'd0),
	.TXSWING(1'd0),
	.TXSYSCLKSEL(1'd0),
	.TXUSERRDY(k7_1000basex_tx_mmcm_locked0),
	.TXUSRCLK(eth_tx_half_clk),
	.TXUSRCLK2(eth_tx_half_clk),
	.CPLLFBCLKLOST(k7_1000basex0),
	.CPLLLOCK(k7_1000basex_pll_lock),
	.CPLLREFCLKLOST(k7_1000basex1),
	.DMONITOROUT(k7_1000basex6),
	.DRPDO(k7_1000basex3),
	.DRPRDY(k7_1000basex4),
	.EYESCANDATAERROR(k7_1000basex9),
	.GTREFCLKMONITOR(k7_1000basex5),
	.GTXTXN(sgmii_txn),
	.GTXTXP(sgmii_txp),
	.PCSRSVDOUT(k7_1000basex42),
	.PHYSTATUS(k7_1000basex7),
	.RXBUFSTATUS(k7_1000basex14),
	.RXBYTEISALIGNED(k7_1000basex20),
	.RXBYTEREALIGN(k7_1000basex21),
	.RXCDRLOCK(k7_1000basex10),
	.RXCHANBONDSEQ(k7_1000basex23),
	.RXCHANISALIGNED(k7_1000basex25),
	.RXCHANREALIGN(k7_1000basex26),
	.RXCHARISCOMMA(k7_1000basex39),
	.RXCHARISK({k7_1000basex_rx_data0[18], k7_1000basex_rx_data0[8]}),
	.RXCHBONDO(k7_1000basex24),
	.RXCLKCORCNT(k7_1000basex11),
	.RXCOMINITDET(k7_1000basex37),
	.RXCOMMADET(k7_1000basex22),
	.RXCOMSASDET(k7_1000basex35),
	.RXCOMWAKEDET(k7_1000basex36),
	.RXDATA({k7_1000basex_rx_data0[17:10], k7_1000basex_rx_data0[7:0]}),
	.RXDATAVALID(k7_1000basex31),
	.RXDLYSRESETDONE(k7_1000basex15),
	.RXELECIDLE(k7_1000basex38),
	.RXHEADER(k7_1000basex32),
	.RXHEADERVALID(k7_1000basex33),
	.RXMONITOROUT(k7_1000basex27),
	.RXNOTINTABLE(k7_1000basex13),
	.RXOUTCLK(k7_1000basex_rxoutclk),
	.RXOUTCLKFABRIC(k7_1000basex29),
	.RXOUTCLKPCS(k7_1000basex30),
	.RXPHALIGNDONE(k7_1000basex16),
	.RXPHMONITOR(k7_1000basex17),
	.RXPHSLIPMONITOR(k7_1000basex18),
	.RXPRBSERR(k7_1000basex12),
	.RXQPISENN(k7_1000basex40),
	.RXQPISENP(k7_1000basex41),
	.RXRATEDONE(k7_1000basex28),
	.RXRESETDONE(k7_1000basex_rx_reset_done),
	.RXSTARTOFSEQ(k7_1000basex34),
	.RXSTATUS(k7_1000basex19),
	.RXVALID(k7_1000basex8),
	.TSTOUT(k7_1000basex2),
	.TXBUFSTATUS(k7_1000basex46),
	.TXCOMFINISH(k7_1000basex51),
	.TXDLYSRESETDONE(k7_1000basex43),
	.TXGEARBOXREADY(k7_1000basex50),
	.TXOUTCLK(k7_1000basex_txoutclk),
	.TXOUTCLKFABRIC(k7_1000basex47),
	.TXOUTCLKPCS(k7_1000basex48),
	.TXPHALIGNDONE(k7_1000basex44),
	.TXPHINITDONE(k7_1000basex45),
	.TXQPISENN(k7_1000basex52),
	.TXQPISENP(k7_1000basex53),
	.TXRATEDONE(k7_1000basex49),
	.TXRESETDONE(k7_1000basex_tx_reset_done)
);

BUFG bufg_txoutrebuf(
	.I(k7_1000basex_txoutclk),
	.O(k7_1000basex_txoutclk_rebuffer)
);

BUFG bufg_rxoutrebuf(
	.I(k7_1000basex_rxoutclk),
	.O(k7_1000basex_rxoutclk_rebuffer)
);

BUFG bufg_ethtx62(
	.I(k7_1000basex_s7mmcm0_clkout0),
	.O(k7_1000basex_s7mmcm0_clkout_buf0)
);

BUFG bufg_ethtx125(
	.I(k7_1000basex_s7mmcm0_clkout1),
	.O(k7_1000basex_s7mmcm0_clkout_buf1)
);

BUFG bufg_ethrx62(
	.I(k7_1000basex_s7mmcm1_clkout0),
	.O(k7_1000basex_s7mmcm1_clkout_buf0)
);

BUFG bufg_ethrx125(
	.I(k7_1000basex_s7mmcm1_clkout1),
	.O(k7_1000basex_s7mmcm1_clkout_buf1)
);

FDCE FDCE(
	.C(k7_1000basex_s7mmcm0_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(k7_1000basex_tx_mmcm_reset1),
	.Q(s7mmcm0_reset0)
);

FDCE FDCE_1(
	.C(k7_1000basex_s7mmcm0_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm0_reset0),
	.Q(s7mmcm0_reset1)
);

FDCE FDCE_2(
	.C(k7_1000basex_s7mmcm0_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm0_reset1),
	.Q(s7mmcm0_reset2)
);

FDCE FDCE_3(
	.C(k7_1000basex_s7mmcm0_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm0_reset2),
	.Q(s7mmcm0_reset3)
);

FDCE FDCE_4(
	.C(k7_1000basex_s7mmcm0_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm0_reset3),
	.Q(s7mmcm0_reset4)
);

FDCE FDCE_5(
	.C(k7_1000basex_s7mmcm0_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm0_reset4),
	.Q(s7mmcm0_reset5)
);

FDCE FDCE_6(
	.C(k7_1000basex_s7mmcm0_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm0_reset5),
	.Q(s7mmcm0_reset6)
);

FDCE FDCE_7(
	.C(k7_1000basex_s7mmcm0_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm0_reset6),
	.Q(s7mmcm0_reset7)
);

MMCME2_ADV #(
	.BANDWIDTH("OPTIMIZED"),
	.CLKFBOUT_MULT_F(5'd18),
	.CLKIN1_PERIOD(16.0),
	.CLKOUT0_DIVIDE_F(5'd18),
	.CLKOUT0_PHASE(1'd0),
	.CLKOUT1_DIVIDE(4'd9),
	.CLKOUT1_PHASE(1'd0),
	.DIVCLK_DIVIDE(1'd1),
	.REF_JITTER1(0.01)
) MMCME2_ADV (
	.CLKFBIN(s7mmcm0_mmcm_fb),
	.CLKIN1(k7_1000basex_s7mmcm0_clkin_signal),
	.PWRDWN(k7_1000basex_tx_mmcm_power_down),
	.RST(s7mmcm0_reset7),
	.CLKFBOUT(s7mmcm0_mmcm_fb),
	.CLKOUT0(k7_1000basex_s7mmcm0_clkout0),
	.CLKOUT1(k7_1000basex_s7mmcm0_clkout1),
	.LOCKED(k7_1000basex_tx_mmcm_locked1)
);

FDCE FDCE_8(
	.C(k7_1000basex_s7mmcm1_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(k7_1000basex_rx_mmcm_reset1),
	.Q(s7mmcm1_reset0)
);

FDCE FDCE_9(
	.C(k7_1000basex_s7mmcm1_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm1_reset0),
	.Q(s7mmcm1_reset1)
);

FDCE FDCE_10(
	.C(k7_1000basex_s7mmcm1_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm1_reset1),
	.Q(s7mmcm1_reset2)
);

FDCE FDCE_11(
	.C(k7_1000basex_s7mmcm1_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm1_reset2),
	.Q(s7mmcm1_reset3)
);

FDCE FDCE_12(
	.C(k7_1000basex_s7mmcm1_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm1_reset3),
	.Q(s7mmcm1_reset4)
);

FDCE FDCE_13(
	.C(k7_1000basex_s7mmcm1_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm1_reset4),
	.Q(s7mmcm1_reset5)
);

FDCE FDCE_14(
	.C(k7_1000basex_s7mmcm1_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm1_reset5),
	.Q(s7mmcm1_reset6)
);

FDCE FDCE_15(
	.C(k7_1000basex_s7mmcm1_clkin_signal),
	.CE(1'd1),
	.CLR(1'd0),
	.D(s7mmcm1_reset6),
	.Q(s7mmcm1_reset7)
);

MMCME2_ADV #(
	.BANDWIDTH("OPTIMIZED"),
	.CLKFBOUT_MULT_F(5'd18),
	.CLKIN1_PERIOD(16.0),
	.CLKOUT0_DIVIDE_F(5'd18),
	.CLKOUT0_PHASE(1'd0),
	.CLKOUT1_DIVIDE(4'd9),
	.CLKOUT1_PHASE(1'd0),
	.DIVCLK_DIVIDE(1'd1),
	.REF_JITTER1(0.01)
) MMCME2_ADV_1 (
	.CLKFBIN(s7mmcm1_mmcm_fb),
	.CLKIN1(k7_1000basex_s7mmcm1_clkin_signal),
	.PWRDWN(k7_1000basex_rx_mmcm_power_down),
	.RST(s7mmcm1_reset7),
	.CLKFBOUT(s7mmcm1_mmcm_fb),
	.CLKOUT0(k7_1000basex_s7mmcm1_clkout0),
	.CLKOUT1(k7_1000basex_s7mmcm1_clkout1),
	.LOCKED(k7_1000basex_rx_mmcm_locked1)
);

(* ars_ff1 = "true", async_reg = "true" *) FDPE #(
	.INIT(1'd1)
) FDPE (
	.C(eth_tx_clk),
	.CE(1'd1),
	.D(1'd0),
	.PRE(xilinxasyncresetsynchronizerimpl0),
	.Q(xilinxasyncresetsynchronizerimpl0_rst_meta)
);

(* ars_ff2 = "true", async_reg = "true" *) FDPE #(
	.INIT(1'd1)
) FDPE_1 (
	.C(eth_tx_clk),
	.CE(1'd1),
	.D(xilinxasyncresetsynchronizerimpl0_rst_meta),
	.PRE(xilinxasyncresetsynchronizerimpl0),
	.Q(eth_tx_rst)
);

(* ars_ff1 = "true", async_reg = "true" *) FDPE #(
	.INIT(1'd1)
) FDPE_2 (
	.C(eth_rx_clk),
	.CE(1'd1),
	.D(1'd0),
	.PRE(xilinxasyncresetsynchronizerimpl1),
	.Q(xilinxasyncresetsynchronizerimpl1_rst_meta)
);

(* ars_ff2 = "true", async_reg = "true" *) FDPE #(
	.INIT(1'd1)
) FDPE_3 (
	.C(eth_rx_clk),
	.CE(1'd1),
	.D(xilinxasyncresetsynchronizerimpl1_rst_meta),
	.PRE(xilinxasyncresetsynchronizerimpl1),
	.Q(eth_rx_rst)
);

endmodule
