#!/usr/bin/env python3
"""Assemble the Linux netboot payload for a LiteX SoC.

Two things here must come from the SoC rather than be assumed, and both have
already cost a boot:

  * the UART address in the device tree.  Adding the CPU timer that Linux
    needs shifts every CSR bank, so a dtb written for one build is wrong for
    the next.  It is read from csr.json.

  * `linux,initrd-end`.  It must be the start plus the ACTUAL size of
    rootfs.cpio: round it up and the kernel reads past the archive and
    reports "Initramfs unpacking failed: junk in compressed archive", then
    limps on from /dev/ram0 with tmpfs mounts failing.

The emulator is built separately (see examples/vc707-litex-linux/emulator);
it takes its addresses from generated/csr.h the same way.

Load addresses follow the LiteX convention for a 512 MiB DDR3 at 0x40000000,
and boot.json lists the emulator LAST because the BIOS boots to the address of
the last image unless told otherwise.
"""

import argparse
import json
import os
import re
import subprocess
import sys

KERNEL_ADDR   = 0x40000000
ROOTFS_ADDR   = 0x40800000
DTB_ADDR      = 0x41000000
EMULATOR_ADDR = 0x50000000


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dts",    required=True, help="Device tree source to patch and compile.")
    p.add_argument("--csr",    required=True, help="The SoC's csr.json.")
    p.add_argument("--images", required=True, help="Directory holding Image and rootfs.cpio.")
    p.add_argument("--out",    required=True, help="Where to write the payload (a TFTP directory).")
    # Root over NFS.  The point is development speed: the rootfs stops being a
    # 4 MB cpio rebuilt and re-sent for every change, and becomes a directory on
    # the host that the board reads live.  It also drops rootfs.cpio from the
    # transfer entirely, so netboot moves less over TFTP.
    p.add_argument("--nfsroot", metavar="SERVER:/PATH",
                   help="Boot with root on NFS instead of the initramfs, "
                        "e.g. 192.168.1.106:/home/jonathan/vc707-nfsroot")
    p.add_argument("--ip", default="192.168.1.50", help="Board address for the ip= argument.")
    p.add_argument("--gw", default="192.168.1.1",  help="Gateway for the ip= argument.")
    p.add_argument("--mask", default="255.255.255.0", help="Netmask for the ip= argument.")
    p.add_argument("--iface", default="eth0", help="Board interface for the ip= argument.")
    args = p.parse_args()

    csr  = json.load(open(args.csr))
    uart = csr["csr_bases"]["uart"]

    rootfs = os.path.join(args.images, "rootfs.cpio")
    if not args.nfsroot:
        if not os.path.isfile(rootfs):
            sys.exit(f"no rootfs.cpio in {args.images}")
        initrd_end = ROOTFS_ADDR + os.path.getsize(rootfs)

    dts = open(args.dts).read()
    # Retarget the UART, and ONLY the UART.  This used to rewrite every address
    # matching 0x..f0xxxxxx, which is every CSR bank in the tree: the ethernet
    # MAC's reg became the UART's, so a board booted from a dtb built here had
    # no network at all.  It went unnoticed because the dtb in service was
    # generated by another route.  Scope the substitution to the serial node's
    # own body, and to the alias that names it.
    def retarget(m):
        return m.group(1) + re.sub(r"0x[0-9a-f]{8}", f"0x{uart:08x}", m.group(2), count=1)
    dts = re.sub(r"(serial@[0-9a-f]+\s*\{)([^{}]*\})", retarget, dts, flags=re.S)
    dts = re.sub(r"serial@[0-9a-f]+",  f"serial@{uart:x}", dts)
    if args.nfsroot:
        # The initrd properties must GO, not merely be ignored.  A kernel that
        # finds an initramfs mounts it and never looks at root=, so leaving
        # them in place boots the old rootfs and looks like the NFS mount
        # silently failed.
        dts = re.sub(r"\s*linux,initrd-(start|end)\s*=\s*<[^>]*>;", "", dts)
        server = args.nfsroot.split(":", 1)[0]
        # nolock keeps lockd and statd out of it, which a root filesystem does
        # not need and which would otherwise have to be running on the host.
        rootargs = (f"root=/dev/nfs rw nfsroot={args.nfsroot},vers=3,tcp,nolock "
                    f"ip={args.ip}:{server}:{args.gw}:{args.mask}:vc707:{args.iface}:off")
        dts = re.sub(r"root=/dev/ram0", rootargs, dts)
    else:
        dts = re.sub(r"(linux,initrd-end\s*=\s*<)0x[0-9a-f]+(>)",
                     rf"\g<1>0x{initrd_end:08x}\g<2>", dts)

    os.makedirs(args.out, exist_ok=True)
    dts_out = os.path.join(args.out, "rv32.dts")
    dtb_out = os.path.join(args.out, "rv32.dtb")
    open(dts_out, "w").write(dts)
    subprocess.run(["dtc", "-I", "dts", "-O", "dtb", "-o", dtb_out, dts_out], check=True)

    # The emulator goes last: boot.c takes the boot address from the final
    # image unless a bootargs.addr key says otherwise.
    boot = {"Image": f"0x{KERNEL_ADDR:08x}"}
    if not args.nfsroot:
        boot["rootfs.cpio"] = f"0x{ROOTFS_ADDR:08x}"
    boot["rv32.dtb"]     = f"0x{DTB_ADDR:08x}"
    boot["emulator.bin"] = f"0x{EMULATOR_ADDR:08x}"
    with open(os.path.join(args.out, "boot.json"), "w") as f:
        json.dump(boot, f, indent=4)

    print(f"  uart          0x{uart:08x} (from csr.json)")
    if args.nfsroot:
        print(f"  root          {args.nfsroot} over NFSv3 (no initramfs)")
    else:
        print(f"  initrd        0x{ROOTFS_ADDR:08x}..0x{initrd_end:08x} "
              f"({os.path.getsize(rootfs)} bytes)")
    for name, addr in boot.items():
        print(f"  {name:14} {addr}")


if __name__ == "__main__":
    main()
