# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jonathan/xc7-bitstream-tools/examples/vc707-sdtest/ip/sdtest_ila.srcs/sources_1/ip/sdtest_ila/sdtest_ila.xci
# IP: The module: 'sdtest_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jonathan/xc7-bitstream-tools/examples/vc707-sdtest/ip/sdtest_ila.srcs/sources_1/ip/sdtest_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdtest_ila'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/jonathan/xc7-bitstream-tools/examples/vc707-sdtest/ip/sdtest_ila.srcs/sources_1/ip/sdtest_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdtest_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/jonathan/xc7-bitstream-tools/examples/vc707-sdtest/ip/sdtest_ila.srcs/sources_1/ip/sdtest_ila/sdtest_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdtest_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/jonathan/xc7-bitstream-tools/examples/vc707-sdtest/ip/sdtest_ila.srcs/sources_1/ip/sdtest_ila/sdtest_ila.xci
# IP: The module: 'sdtest_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jonathan/xc7-bitstream-tools/examples/vc707-sdtest/ip/sdtest_ila.srcs/sources_1/ip/sdtest_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdtest_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/jonathan/xc7-bitstream-tools/examples/vc707-sdtest/ip/sdtest_ila.srcs/sources_1/ip/sdtest_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdtest_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/jonathan/xc7-bitstream-tools/examples/vc707-sdtest/ip/sdtest_ila.srcs/sources_1/ip/sdtest_ila/sdtest_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdtest_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
